### ISSUE TITLE
Turning off cluster setting

### ISSUE THREAD

**Issue by rockclimber36** [gameserverapp/Platform#109]
__Please make sure to leave out any sensitive information__!

**Describe the issue**
A clear and concise description of what the issue / improvement is.

**Section**
Startup parameters for ark

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**
If we could turn off clustering setting with ark server then we would be able to upload our characters via terminal and change maps with no worries of loosing our character.

**Comment by rockclimber36** [comment]
https://discord.com/channels/315049169071112193/685253991726317584/948369981136044063
Here is the link per the first message on discord of me asking about this. Was wondering if this is even something possible to do.

**Comment by mvaessen** [comment]
The cluster settings can be disabled by adding `-gsanocluster` to the `end` section on your config template.
