### ISSUE TITLE
Discord card keeps on being posted

### ISSUE THREAD

**Issue by meza** [gameserverapp/Platform#123]
**Describe the bug**
The discord card for one server out of the cluster keeps on getting posted repeatedly every N minutes. I've turned it off for now.

**Expected behavior**
Just one card in the channel especially if nothing has changed with the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/211977/158032088-1f757b19-0200-43ca-8257-4c34b0f0ebbe.png)

**Comment by mvaessen** [comment]
Thanks for your report!
Im closing this item since #49 is addressing the same issue.

Can you provide me with the associated game server ID in #49 please?
