### ISSUE TITLE
task/event log getting placed into deliveries under the user profile. 

### ISSUE THREAD

**Issue by Kriz02** [gameserverapp/Platform#124]
We have a basic task/event that runs every time a player logs on. It will check custom roles to see if they are eligible for a bonus. if they are it gives them the bonus and sets a role for 1 day / 1 week respectively. 

While this system seems to work just fine, it is spamming the delivers section of the user profile with every attempt it makes to check these roles when they come online on any map. While it does label each attempt with a "Task" tag it really makes it difficult to see when the player actually receives a real delivery.

Perhaps a separate tab for Tasks or just let them log them under the current task log.

![user](https://user-images.githubusercontent.com/92939298/158076985-d3e52949-c150-43cd-bb0a-433e954c549e.png)

**Comment by mvaessen** [comment]
This should be fixed now. Thanks for reporting!
