### ISSUE TITLE
Discord Tribe Logs

### ISSUE THREAD

**Issue by Jamacaw** [gameserverapp/Platform#126]
__Please make sure to leave out any sensitive information__!

**Describe the bug**

**To Reproduce**
1. Set up discord tribe logs via community website.
2. Trigger a tribe log in game.
3. Tribe log is never sent regardless of time passed.

**Expected behavior**
Tribe log to be sent to discord within 10 minutes or so.

**Screenshots**

**Additional context**

**Comment by mvaessen** [comment]
Hello,

Upon testing I wasnt able to reproduce the reported issue.

![Screenshot 2022-03-28 at 11 22 06](https://user-images.githubusercontent.com/13402423/160367903-2ebdc3d2-7cc3-4a47-acd8-8dfabbce7150.png)

Could you please:
1. Navigate to: https://dash.gameserverapp.com/admintools/groups
2. Click the tribe / group
3. Click "Log" in the top menu
4. Confirm the tribe logs are listed there

After that, please go to your community website and:
1. Go to Group settings
![Settings_-_Tribe_of_Human_-_GameServerApp_com](https://user-images.githubusercontent.com/13402423/160368414-87991d41-8524-4b22-aecc-913862f320e3.jpg)

2. Connect discord and setup the right channel
![Settings_-_Tribe_of_Human_-_GameServerApp_com](https://user-images.githubusercontent.com/13402423/160369109-2ed6bc85-0aac-43fe-8354-c9035ce97992.jpg)
