### ISSUE TITLE
Chat not properly indexed

### ISSUE THREAD

**Issue by Zoro189** [gameserverapp/Platform#136]
![image](https://user-images.githubusercontent.com/97253893/159578404-453e217d-2701-4505-8ac2-e124cda438f5.png)
![image](https://user-images.githubusercontent.com/97253893/159578487-a3e2032d-16ae-4197-a4c9-a6b8b401a60d.png)
![image](https://user-images.githubusercontent.com/97253893/159578527-693d0883-0736-40bd-b190-0b68598cc519.png)

**Comment by Zoro189** [comment]
event simple trigger like this doesnt work
![image](https://user-images.githubusercontent.com/97253893/159579265-239cb264-01ab-4b45-a5a9-d82cd84d0bf2.png)

**Comment by mvaessen** [comment]
hi, can you include a screenshot of the task settings? I'd like to see the page where is shows what game servers you have selected and whether the task is active.

Please include the chatlog from the dashboard. So i can see what game server this is happening on. Your discord chat log doesnt indicate which server this is.

**Comment by henrik123098** [comment]
![Screenshot_20220323-142807_Samsung Internet](https://user-images.githubusercontent.com/26748382/159710659-27041145-66e1-43c7-b7fa-8a3eb2556dea.jpg)
![Screenshot_20220323-142815_Samsung Internet](https://user-images.githubusercontent.com/26748382/159710665-1574d859-5402-4cd1-8723-1606e6c508b1.jpg)
![Screenshot_20220323-142833_Samsung Internet](https://user-images.githubusercontent.com/26748382/159710667-1e5b4290-1567-4107-946e-a7ddfbe70cac.jpg)
![Screenshot_20220323-142840_Samsung Internet](https://user-images.githubusercontent.com/26748382/159710672-2f1beedc-e0b7-4492-95e0-d9b12a9b8603.jpg)

**Comment by mvaessen** [comment]
Thanks, please also include:

- [ ] screenshot chatlog from the dashboard, where the person is saying the trigger chat word.
- [ ] point out which server that is on the screenshots.

**Comment by henrik123098** [comment]
the server is the Test Rag Bases

![Uploading Screenshot_20220323-151358_Samsung Internet.jpg…]()

**Comment by henrik123098** [comment]
![Uploading Screenshot_20220323-151358_Samsung Internet.jpg…]()

**Comment by mvaessen** [comment]
Can you try launching your game server with the `Default settings (GSA)` config template? See if it still happens after that.

**Comment by mvaessen** [comment]
Hi, any updates on the progress?
let me know if i can close the issue

**Comment by Zoro189** [comment]
We are wiping cluster today so we are little busy. Il try tommorow and post update

**Comment by Zoro189** [comment]
Still not working after trying with default config

**Comment by mvaessen** [comment]
Just ran a test on one of your servers. Local chat seems to be processed fine, while the normal global chat isnt being processed. Based on the `[Missing Message ID: Auto]` in the chat I'm thinking you may be using a plugin that is altering the chat. This can cause issues. Try removing the plugin to resolve the issue.

![Screenshot 2022-03-28 at 09 55 35](https://user-images.githubusercontent.com/13402423/160352320-2fe29b19-2b8e-420f-8400-36987f6eae50.png)
