### ISSUE TITLE
Voting Rewards - API Issues for TopArkServers and Ark-Servers.net

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#158]
**Describe the bug**
**TopArkServers** - the website registers when a vote has been cast by a player and lists it in the database. When claimed in discord, the TopArkServers website lists the reward as claimed. The GSA dashboard logs the vote in its voting history page. However, players are not delivered tokens to their web accounts. 
<img width="866" alt="3e26999137b1d7338556eec238f7ee77" src="https://user-images.githubusercontent.com/44717221/161855952-4f40f01b-47a3-4312-8be8-c3c968fc673d.png">
<img width="639" alt="80293d3a9bb60b34ca7149c08875e498" src="https://user-images.githubusercontent.com/44717221/161856000-3d15863e-d267-43ed-8800-e9f9665890bb.png">
The delivery system lists the delivery as "pending" players coming online. When claiming votes in discord, the bot runs a check, but no announcement is made. I managed to log in and sit around for several minutes, but the delivery system still did not disperse the rewards. 

<img width="762" alt="4e68db7952ecf87b22a3e3de343d3999" src="https://user-images.githubusercontent.com/44717221/161856013-53479a83-68bd-4f65-acd8-9ca1a0ae1543.png">
<img width="1034" alt="cd59d2b4c5b117e94d3ee8c147fcdefa" src="https://user-images.githubusercontent.com/44717221/161856107-06f5de7b-0aa5-4e29-ac37-b6375bb37c9e.png">
https://user-images.githubusercontent.com/44717221/161856432-b4c270df-3cf6-4cfa-9b08-3ca85147b74c.mp4

In addition, some API keys from TopArkServers are not registering as being legitimate on the GSA dashboard, despite being directly copied correctly from TopArkServers. 
<img width="686" alt="f8898a9807714605e71ddb587b163863" src="https://user-images.githubusercontent.com/44717221/161856639-24324823-ae48-481a-af9e-47400772f70c.png">

**Ark-Servers.net** - While the API keys say that they're valid, no rewards are issued after players vote for the servers through Ark-Servers.net. In addition, GSA does not record in the voting log when votes are made through this website. 
<img width="516" alt="809800318c5559bebc327037cadf14a1" src="https://user-images.githubusercontent.com/44717221/161863433-650368d5-6d54-43c3-bd23-bede8d31d4e4.png">

**Comment by mvaessen** [comment]
Both #160 and the validation issues with the TopArkServers api are resolved. They made some changes to their API that caused the validation to fail.

**Comment by mvaessen** [comment]
Upon testing ark-servers.net i could not find any issues. I registered the server, casted a vote via steam and claimed it. The vote show up on the claimed vote log.

**Comment by Decollates** [comment]
Reopening due to continued issues:

Player cast a vote and attempted to claim the rewards. The result was a failure to deliver the vote rewards pack up to 5 times before GSA's logic gave up. 

<img width="484" alt="d924a3d08a9d6e211b4d523cf77dffdb" src="https://user-images.githubusercontent.com/44717221/162797265-4a6393a3-e540-4c5a-97f3-9c6524098747.png">
<img width="1041" alt="9f1a9c78dc4fb9357fcae07f9002fb36" src="https://user-images.githubusercontent.com/44717221/162797285-ce8b105e-2209-4227-aa16-ea9849b8300e.png">

[This is a link](https://dash.gameserverapp.com/monetization/deliveries/v2/delivery/2708071) to the delivery details of one of the failed attempts.
[This is a link](https://dash.gameserverapp.com/community/vote-rewards/reward/235/edit) to the voter rewards pack that is supposed to reward players for voting. 

In addition, TopArkServers' API keys seem to still not successfully connect for voter rewards. For the voter rewards pack, it was initially intended just for our PvE Ragnarok server, but to better troubleshoot, I included all other PvE servers into the setting's conditions. 
<img width="279" alt="33ab91df81e3ebf771ecb358b5bc0367" src="https://user-images.githubusercontent.com/44717221/162797875-fb89316a-cd2b-4482-8880-0b690cec4cda.png">

**Comment by mvaessen** [comment]
Hi, I opened a separate issue (#167) for the issue with the delivery, to make things manageable.
This issue is dedicated to the API issues with TopArkServers.

Did you had any chance talking to them about the api issues since you mentioned it yesterday?

**Comment by Decollates** [comment]
Understood. I had a conversation with one of their admins, and they insist that everything is working normally.

I can DM or email you the Server API Details link if need be. 
<img width="532" alt="275c0a18ae970ad5ed08bb929502c451" src="https://user-images.githubusercontent.com/44717221/163017276-50dce157-a7d5-41b6-847d-01a28c1af3e3.png">
<img width="510" alt="Screenshot 2022-04-12 095628" src="https://user-images.githubusercontent.com/44717221/163017292-b8d3fbb3-2a4d-495f-933d-2aa7d4de8f5e.png">

**Comment by mvaessen** [comment]
Hi, I tested it again and can't reproduce the issues.
make sure your game server is on when you validate the API key, because TopArkServers doesn't provide valid API information when the game server is off (kinda annoying).

How to fix:
1. Remove the API key from the form
2. Save the form
3. Confirm the API key field shows a `?` icon
4. Enter the API key again
5. Save the form
