### ISSUE TITLE
Voting Rewards - API Issues for TopConanServers 

### ISSUE THREAD

**Issue by Sarpendon** [gameserverapp/Platform#160]
API Key Validation Failed at Voting Reward Settings for TopConanServers.com

**Describe the bug**
API Key won't be accepted for TopConanServers.com 

**To Reproduce**
1. Go to Community
2. Click on Vote rewards
3. Select Settings

**Screenshots**
https://i.imgur.com/xDW6VpB.png

**Comment by mvaessen** [comment]
This issue seems a duplicate of #158
