### ISSUE TITLE
Deleted players show up on token transaction delivery options

### ISSUE THREAD

**Issue by OsidianKingVIII** [gameserverapp/Platform#169]
A player has had 4 characters on the cluster. 2 of them exist and 2 of them are deleted because they existed on a deleted server. 

When player attempts to make transaction all 4 players are offered as an option. When the player uses the deleted server character they do not get any rewards. 

However when I manually attempt to send the transaction it only lists the 2 existing characters, as it should. 

I am able to manually delete the deleted server characters. However it would be best if the website filtered them out so they are not an option for delivery.

**Comment by mvaessen** [comment]
Hi, can you include links to the character and the associated game server id's please?

**Comment by OsidianKingVIII** [comment]
I dont think i can because i manually deleted the deleted-characters in GSA
today. i did it to prevent it from happening because the player used the
same character name "Bunny", one was deleted the other wasnt.

heres what i got

f93d1d21-5d98-4f04-ad44-99bf061e2a8c - Delivery details - GameServerApp.com
<https://dash.gameserverapp.com/monetization/deliveries/v2/delivery/2787071>


Game server ID:12637

**Comment by mvaessen** [comment]
Hi, based on the currently provided info I cant investigate. If you have screenshots of the situation you described and links to pages where it happens please do post.

**Comment by mvaessen** [comment]
Closing due to lack of info to work with
