### ISSUE TITLE
Vote Rewards setup generating wrong link for the in-game vote menu.

### ISSUE THREAD

**Issue by MeganJClark** [gameserverapp/Platform#177]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
In-game vote links occasionally generate links to a missing page. The page exists but the link generated by the Vote Rewards Settings page in-game does not go to that page. 

**To Reproduce**
1. Go to Vote Rewards
2. Click on Settings
3. Scroll down to correct serve, enter API key
4. An in-game link opens to wrong voting page (wrong ip)

**Expected behavior**
Expect a link to open an accurate page to vote for the server.

**Actual Behavior**
The link generated goes to https://toparkservers.com/server/142.44.143.174:27015/vote but should go to https://toparkservers.com/server/142.44.143.208:27015/vote

**Additional context**
Contact me in discord at Pennylane#1771 and I will give you the API key for the bad link.

**Comment by mvaessen** [comment]
Hello,

Thank you for the report.

I tried reproducing the issue but was not able to. The link is always showing the right port for me.
Could you provide a before & after screenshot showing the game server name, to rule out any issues?

**Comment by MeganJClark** [comment]
Setup:
![image](https://user-images.githubusercontent.com/7552667/168301286-5196d0b7-4cb2-4932-a934-480d52565801.png)
This is the API key for Trackyserver and my Lost Island Map
![image](https://user-images.githubusercontent.com/7552667/168301469-7e295e97-ae20-449e-90ef-56ada88455d6.png)
The correct Trackyserver page:
![image](https://user-images.githubusercontent.com/7552667/168301720-a341a56c-78e4-4a86-82b8-faa935251ed8.png)
The page the in-game link takes us to: 
![image](https://user-images.githubusercontent.com/7552667/168301802-3b70d55d-d5e8-4e96-a51a-3f71472fa890.png)

**Comment by MeganJClark** [comment]
Submitted

**Comment by mvaessen** [comment]
Hi @MeganJClark,

Thanks! I removed the message because it was showing api keys.

I was able to look at the screens and I noticed you showed Trackyserver links in your examples. Based on your initial report I assumed the issue was with toparkservers.com links, so i only tested those.

I will take a new look and test the trackyservers links this time.

**Comment by MeganJClark** [comment]
> Hi @MeganJClark,
> 
> Thanks! I removed the message because it was showing api keys.
> 
> I was able to look at the screens and I noticed you showed Trackyserver links in your examples. Based on your initial report I assumed the issue was with toparkservers.com links, so i only tested those.
> 
> I will take a new look and test the trackyservers links this time.

When I submitted it was TopArk. It's taken me a few weeks to decide to submit because the affected link has changed or disappeared entirely. I thought it was a problem with the tracking sites until it switched from Tracky to TopArk and now back again

**Comment by mvaessen** [comment]
Problem was resolved over Discord.

Issue was related to a missing Server ID, in the form. In the upcoming update the system will throw an error when the Server ID is missing.
