### ISSUE TITLE
Can't Add a Voting Site

### ISSUE THREAD

**Issue by Krysez** [gameserverapp/Platform#187]
**Describe the bug**
The Add a Voting Site button does not appear in my service.

**To Reproduce**
1. Go to 'Voting Rewards'
2. Click on 'Settings
3. See error

**Expected behavior**
There should be a button to add a Voting site.

**Screenshots**
![image](https://user-images.githubusercontent.com/17150924/171492157-a465ea7f-76c7-4e22-99e7-616796fa7e75.png)

**Additional context**
I am trying to add the TopConanServers and TrackyServer API

**Comment by mvaessen** [comment]
Hello,

If your game server is unhealthy it may not show up on the list. What GSA product are you using?

**Comment by Krysez** [comment]
Hello Max, I am using the RCon feature. But I posted in the issue comments that it suddenly started working. Maybe cause I just purchased the upgrade and it was settling. 
Thanks for checking in

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 1, 2022 at 4:54 PM, Max ***@***.***> wrote:   


Hello,

If your game server is unhealthy it may not show up on the list. What GSA product are you using?

**Comment by mvaessen** [comment]
Okido. Most likely it was an unhealthy status in that case. The system checks for that every 10 minutes.

I'll close the issue 👍
