### ISSUE TITLE
Empty backup page scrolling oddly.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#197]
Just fired up a new server so it has no backups. When I try to scroll down to get to the enable automatic backups button it jumps the page backup a few lines. It does not do this on other servers with backups present.

**Comment by mvaessen** [comment]
Ah, i've seem this happen to me as well. It's related to the sticky sidebar (right) when the page content (middle) is shorter than the sidebar. Thanks for the reminder!

**Comment by mvaessen** [comment]
Fixed, thanks for reporting!
