### ISSUE TITLE
Unable to open players whitelist settings.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#205]
**Describe the bug**
unable to load a players whitelist on their profile.

**To Reproduce**
1. Go to a player's profile
2. Click on whitelist tab
3. Fail to go anywhere.

**Expected behavior**
The whitelist page to open

**Additional context**
Open in new tab does work.

**Comment by mvaessen** [comment]
Hello,

I tried reproducing but the whitelist tab opens just fine for me. Can you provide me the link you're testing this for? Can you also include the type of browser you're using?

**Comment by birdman3131** [comment]
After a bit of further testing it appears to be an extension I have for making phone calls possible from a website phone number.  Sorry about that. 

Chrome with FOP2
