### ISSUE TITLE
Enable backups for 7 Days to Die

### ISSUE THREAD

**Issue by ronnocnave** [gameserverapp/Platform#231]
Per Discord discussion:

it seems that the backup is too big indeed. Last time i increase the max. backup size limit. It seems that your backups are hitting that new limit. Have you considered using DediConnect? That comes without any limits regarding backup size.

The backups can't be THAT big. It's just a normal 7 Days server...
Max — Today at 3:20 PM
For 7d2d the map is backed up as well i believe, which amounts to quite a large backup
The reason i suggested dediconnect is because it has no limits, due to it being hosted on your own hardware. For GSA:Hosted there are safety limits to avoid issues due to large backups

DownIncognito — Today at 4:13 PM
Understood. So what are my options at the end of the day? Find another hosting provider (I don't want this), or get my own server and use Dedi?

Max — Today at 4:23 PM
Could you create an 🏗-issues-and-dev for me about the backup size issue you experienced? I’ll try look into it this week. Not sure if there is anything I can tweak further for 7d2d, but maybe there is something i can do. Dediconnect is always an option, especially if you’re hosting multiple servers.

DownIncognito — Today at 4:35 PM
Only 1 server 

NOTE: Tried to post in the appropriate Discord channel suggested, but did not have access to post there. 

Game server ID:
12388

**Comment by mvaessen** [comment]
Thanks for posting the issue on Github!

I'll try to check this out today, depending on how today's release goes. Otherwise it'll be somewhere this week.

**Comment by mvaessen** [comment]
Hi, I've made some changes to the system. It now allows creating backups up to 1.5GB.

**Comment by ronnocnave** [comment]
Thank you!
