### ISSUE TITLE
Whoops! Deleting an achievement

### ISSUE THREAD

**Issue by newtarkprojects** [gameserverapp/Platform#233]
**Describe the bug**
I have some achievements in a group that are turned off, I am trying to delete them. Each time I try to delete them from the groups overview, I get the Whoops! A bug page.

**To Reproduce**
1. Go to Automate / tasks
2. Create an achievement 
3. Turn the achievement on
4. Turn off the achievement 
5. click on group where the task lives
6. Go to the turned-off task and press the down arrow for the menu
7. Click delete
8. Whoops! Bug page

**Expected behavior**
For the task to be deleted and vanish from the dashboard (or archived)

**Screenshots**
![image](https://user-images.githubusercontent.com/48177364/179795886-d7043e7b-24d7-4631-9c13-64e446a0661a.png)

**Additional context**
As you can see from the screenshot, I have others that are turned off, all failed except one, which is the bottom 200 hours game play task.

Thank you,
Gem

**Comment by mvaessen** [comment]
Thanks reporting! Should be fixed now!

**Comment by newtarkprojects** [comment]
Thank you Max, I can confirm the issue is now fixed for me :)
