### ISSUE TITLE
Achievement not working propperly. 

### ISSUE THREAD

**Issue by Sarpendon** [gameserverapp/Platform#234]
**Describe the bug**
- Created 15 Achievements with different conditions related to playtime X.
- Got triggered once and only one active player recived all achievements no one else.

**To Reproduce**
1. Go to Automate / tasks
2. Create new Achievement
3. Set up condition and rewards
4. wait an hour
5. somehow only 1 out of many player recive achievements 

**Expected behavior**
All players that meet the requirements should maybe get the achievement. 

**Screenshots**
https://i.imgur.com/EgGN8XA.png

https://i.imgur.com/2sL7PgL.png

https://i.imgur.com/7JTU0Sw.png

**Additional context**

**Comment by mvaessen** [comment]
Hi, achievements are handed out at different intervals and based on different events. For players to receive a "Player played X total hours" they need to be online and playing. Every 10 minutes their time is updated and when all conditions are satisfied the achievement is rewarded. 

Please note that the achievements you created are for `total hours played`. You show the player level overview, these are 2 separate things. If you want to reward players based on their level, you should create an achievement for `character reached level X`

**Comment by Sarpendon** [comment]
Hi and thanks for the quick reply. Yes I understood the difference between level and played hours, what I wanted to visualize with the last Screenshot was the amount of players online almost all meet at least one or more requirements to recive an achivement but only one gets them.

For example every achivement will be triggered in steps of 50 hours ( 100/150/200... etc)

here are two examples of around 20 active players that meet the requirements but didn't get any achievement. 

https://i.imgur.com/atUVUC8.png

https://i.imgur.com/atUVUC8.png

**Comment by mvaessen** [comment]
The system will give the achievement for 50 to everyone that is 50 or higher. So it should work as long as they are above 50.

would you mind posting the link to one of the players for which the achievement hasnt been awarded? That should allow me to do some further investigation. Probably will be in the morning :)

**Comment by Sarpendon** [comment]
yeah no worries it's not that important anyway just was wondering why one player got them all and no one else. 

This is the player that got all achievments 

https://i.imgur.com/clY7vkR.png

https://i.imgur.com/KjvSDH1.png

**Comment by mvaessen** [comment]
please post the direct dashboard link so i can look up the right info 👍

**Comment by Sarpendon** [comment]
https://dash.gameserverapp.com/admintools/accounts/20c04065-2845-420f-9ac6-83c1da69dc60
