### ISSUE TITLE
Discord Logs

### ISSUE THREAD

**Issue by Jamacaw** [gameserverapp/Platform#241]
__Please make sure to leave out any sensitive information__!

**Describe the bug**

**To Reproduce**
1. Go to the `Logs` page under the `Configure` category.
2. Go to the `Settings` tab.
3. Configure the `Report logs to Discord` section.
4. Perform an action that is logged.
5. Observe that the Discord log says `You` regardless of who did the action.

**Expected behavior**
Expected the Discord log to show the person who performed the action.

**Screenshots**
![image](https://user-images.githubusercontent.com/57233204/181390951-39a3dfc9-a782-434c-a06d-78b1190425f4.png)

**Additional context**

**Comment by mvaessen** [comment]
Hi, thanks for reporting. This issue should be fixed now.
Please reopen this issue still exists
