### ISSUE TITLE
None of the Rust Wipes(automated) are working for me

### ISSUE THREAD

**Issue by Kevvv-IL** [gameserverapp/Platform#257]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I have tried both methods of task scheduled wipe, and nothing happens after the server gets restarted.

**To Reproduce**

**Expected behavior**
Server info to be wiped. Im not sure what the the expected outcome of each one is specifically, but nothing changes.

**Comment by mvaessen** [comment]
Hello,

Thank you for reporting! I was able to confirm that there were indeed issues with using this feature on Windows machines.
The issue should be resolved now.

Please try again. If the issues persist, please include detailed steps how to reproduce.
