### ISSUE TITLE
Shop in ark

### ISSUE THREAD

**Issue by dewdiddy** [gameserverapp/Platform#260]
__Please make sure to leave out any sensitive information__!
Not sure whats causing it but on my ark server the shop wont load even tho the mod is loaded. Ive had to reinstall or reboot to fix it
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by mvaessen** [comment]
Without providing any of the requested info I'm not even going to bother looking into this.
