### ISSUE TITLE
Maps shown incorrectly 

### ISSUE THREAD

**Issue by Blackchaos23** [gameserverapp/Platform#268]
Hi there,  I'm using the rconconnect feature and we have 13 maps currently running. On the character screen of the dashboard section it's showing the island map for everyone. 
![Screenshot_20220922-172052_Chrome](https://user-images.githubusercontent.com/114191591/191853402-8b5af9dd-1917-411e-8596-4dfdc0f9e7a3.jpg)

**Comment by mvaessen** [comment]
Hi, thanks for reporting!
The issue should be resolved now. The system will slowly populate the map name for your rconconnect servers.
