### ISSUE TITLE
Minecraft support

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#275]
- [x] Allow selecting Java version

Frameworks (to be decided)
- [ ] MinecraftForge
- [x] Spigot
- [ ] BungeeCord
- [ ] FTB

Drop / update guides:
- [ ] https://help.gameserverapp.com/article/209-install-minecraft-forge

**Comment by newtarkprojects** [comment]
Add console support like ARK has. Some commands send back responses which can not be accessed without a console.

**Comment by mvaessen** [comment]
https://api.papermc.io/docs/swagger-ui/index.html?configUrl=/openapi/swagger-config#/projects-controller/projects
https://hangar.papermc.io/api-docs

**Comment by mvaessen** [comment]
> Add console support like ARK has. Some commands send back responses which can not be accessed without a console.

@newtarkprojects unfortunately there currently is no support for console output for Minecraft. This is mostly due to there being no rcon command to get the console output. In order to support that we'd need to add custom stuff to process the log files. which require a bit more work then one might expect unfortunately

**Comment by mvaessen** [comment]
> Add console support like ARK has. Some commands send back responses which can not be accessed without a console.

i got good news for you Gem! It's coming 🔜  ;)

**Comment by newtarkprojects** [comment]
Amazing work Max!
