### ISSUE TITLE
Valheim Gameservercard

### ISSUE THREAD

**Issue by GERDragon** [gameserverapp/Platform#280]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
In the Game Server Card, the Map should be the seed name. 
Also, the player setting is currently 10 players. If you have 70 in server settings, it also takes 70 into the server card. It can be changed in settings of the server. 

**To Reproduce**
1. Go to 'Discord on the Dashboard
2. Click on 'Game Server Card and select Valheim Server'
3. See the error on Discord

**Screenshots**
![image](https://user-images.githubusercontent.com/99832504/195906807-fa80634c-c0f2-489d-ba8f-9b617a9b3e46.png)

**Comment by GERDragon** [comment]
Also happening on Minecraft.
Map Name: The Island

![image](https://user-images.githubusercontent.com/99832504/196040758-d7a3a167-f3a8-4efb-ad24-6b86eab644c3.png)

**Comment by mvaessen** [comment]
When changing the slot limit via the dashboard the number does show up properly:
![slot-limit](https://user-images.githubusercontent.com/13402423/203314889-c718c41b-7b73-4e8b-87e9-6bfd10ae051c.jpg)
![slots](https://user-images.githubusercontent.com/13402423/203314987-48890858-3262-44b5-bbff-d87416c49f6f.jpg)

**Comment by mvaessen** [comment]
Im not sure whether people always want to share their seed. This can be considered a secret.

For now it will remove the map information, when the game does not support custom maps.
