### ISSUE TITLE
First Server being FTP path causing permission issues

### ISSUE THREAD

**Issue by ecoay** [gameserverapp/Platform#288]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Since the first game server you install is also the symbolic links on the FTP server you are unable to set permissions correctly on that server. Plugins and mods that write to the SaveGame folder work on every map except the initial that is also FTP

**To Reproduce**
1. Go to 'gamevserverapp/containers/iyiilumkm
2. Click on 'server files them shoot game and follow to SavedGame

**Expected behavior**
On all other maps aside from initial map plugin can /upload items and also access cloud storage. However initial map attached to ftp server cannot grant high enough permissions to do so and plugins/mods that require symbolic linking are not working within that server.

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by mvaessen** [comment]
Hi,

Can you please elaborate what you mean with "except the initial that is also FTP"? There is no difference between the first, second or thousands game server you install. They all use the same FTP setup.

In addition, it's not clear to me what exactly you're trying to achieve. Can you maybe explain with more details what you're trying to do?

**Comment by ecoay** [comment]
The first game server I installed is the only container with FTP files in it I am trying to set permissions on that container to be able to read and right to the symbolic link folders. I can do it with the other 4 game servers and the only difference I see between my first game server and the other 4 is there isn't full permissions and there is a folder within called FTP 
![Screenshot_20221024-100712_Microsoft Remote Desktop](https://user-images.githubusercontent.com/10067557/197560300-f87e9e52-05d4-48f2-b3fd-fa699c0b732e.jpg)
So I just assumed I couldn't set permissions correctly cause that is where the ftp connects

**Comment by ecoay** [comment]
Not only is this server not reading and writing to the SavedGame folder correctly
![Screenshot_20221024-100926_Microsoft Remote Desktop](https://user-images.githubusercontent.com/10067557/197560985-d28d22b9-d65e-46cc-9775-11a4b0d60b3c.jpg)

But also Lethals Items+ and Tribe Enforcement work on all servers but the initial. Again it was an assumption because that folder also is how I connect to it via FTP is the reason why the permissions to that container aren't working as anticipated

**Comment by ecoay** [comment]
> 

I use shadow storage that is an off map storage system and it works on the other 4 containers as anticipated. Also Lethals Items plus tribute/upload and download works on the other 4 containers as does the tribe enforcement. It's just the initial container that does not work

**Comment by mvaessen** [comment]
An ARK server not reading / writing to the SaveGames folder is most likely a configuration issue (config). Either way, this has nothing to do with FTP settings. Messing with symbolic links, or making any changes via RDP for that matter, can ruin the entire setup. I do not recommend making such changes.

If you think there is an issue with the FTP for your first game server, try reinstalling the game server via the Danger zone section. This should resolve any FTP issues. If it still doesnt work after that, make sure your machine is not blocking any traffic
