### ISSUE TITLE
Minor discord name bug

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#291]
It looks like if a player updates their name on discord it does not get updated on the dashboard leaving some confusion as to who they are.

https://dash.gameserverapp.com/admintools/accounts/fad58fcb-373a-4a1a-a3d2-bc60ec1749a0 in paticular has changed to have the name Journyman with the same nubers after it. 

Nothing pressing just thought you should know.

**Comment by mvaessen** [comment]
Thanks for reporting!
Added an auto-updater, that will check for updates once a week.
