### ISSUE TITLE
Valheim not saving on restart/shutdown or update

### ISSUE THREAD

**Issue by GERDragon** [gameserverapp/Platform#301]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
The automatic world save is not working. Even though it's saying it does one, it wont work

**To Reproduce**
1. Play on a Server 
2. Build something
3. do not in-game save, restart the server
4. reconnect on the server, things are gone / resetted to the last save point

**Expected behavior**
GSA says that's saving the world on restarts/shutdowns or updates. We lost some hours of gameplay because of that :D

**Comment by mvaessen** [comment]
Discussed on Discord. Is most likely caused by big update that was launched the day before.
Not sure if this is a config issue or related to something else. 

Please reopen if this issue persists.
