### ISSUE TITLE
Problem with EOS and 7dtd servers on Windows.

### ISSUE THREAD

**Issue by ad3d0** [gameserverapp/Platform#323]
Using DediConnect freshly installed and fully updated Windows Server 2019. After installing fresh new 7 Days to Die server with default config and no settings changed it has issue reaching EOS which result in server not being registered properly and becoming unjoinable despite technically being online. ("Server still initializing" message if you try joining it)
But if you manually deploy new 7dtd server on the same machine just outside the GSA it runs fine and gets registered properly. I've attached both server logs, first from server run by GSA and second from server manually installed on same server machine.
[GSA server log.log](https://github.com/gameserverapp/Platform/files/10405368/GSA.server.log.log)
[non GSA server log.txt](https://github.com/gameserverapp/Platform/files/10405369/non.GSA.server.log.txt)

1. Install new 7dtd server on Windows machine using GSA
2. Change no setting and start it.
3. Open server log
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: invalid HTTP response code received. URL: https://api.epicgames.dev/sdk/v1/default?platformId=WIN, HTTP code: 0, content length: 0, actual payload size: 0`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: request failed, libcurl error: 60 (Peer certificate cannot be authenticated with given CA certificates)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 0 (  Trying 34.227.136.149...)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 1 (TCP_NODELAY set)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 2 (Connected to api.epicgames.dev (34.227.136.149) port 443 (#0))`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 3 (ALPN, offering http/1.1)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 4 (Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 5 (TLSv1.3 (OUT), TLS handshake, Client hello (1):)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 6 (TLSv1.3 (IN), TLS handshake, Server hello (2):)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 7 (TLSv1.2 (IN), TLS handshake, Certificate (11):)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 8 (TLSv1.2 (OUT), TLS alert, Server hello (2):)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 9 (SSL certificate problem: unable to get local issuer certificate)`
`WRN [EOS] [LogHttp - Warning] 00000226CF7B6220: libcurl info message cache 10 (Closing connection 0)`
`WRN [EOS] [LogHttp - Warning] Lockout of 2.666829s on https://api.epicgames.dev/sdk/v1/default?platformId=WIN`

**Expected behavior**
Proper server registration in EOS looks like this in server logs
`INF [EOS] Server registered, session: 2a06c0b911e24f159c65b3dba5e0f486`
`INF [EOS] Session address: 194.158.122.156`

**Comment by mvaessen** [comment]
Hi,

I pushed an update to resolve the certificate problem.

Please make sure to follow the steps below, to ensure the update is applied on your system:

1. Turn off all game servers that run 7d2d.
2. On the machine, open Powershell and run `docker image ls`
3. Look for `gameserverapp-7d2d` and copy the id from the `IMAGE ID` column
4. Run `docker image rm {insert image id} --force` -> confirm it was succesfully deleted
5. Navigate to `C:\GameserverApp\docker` and delete the `gameserverapp-7d2d` folder
6. Go to 1 (ONE) of your game servers and reinstall it via the dashboard. You only have to do this for 1 game server. 

Let me know if the issue persist or if the problem was resolved after this.

**Comment by ad3d0** [comment]
Thank you very much! Followed your instructions and problem is solved now. Just had to remove containers for all 7dtd servers as they still were trying to use old image.
