### ISSUE TITLE
Server Slider on Community Website

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#326]
### Discussed in https://github.com/gameserverapp/Platform/discussions/324

<div type='discussions-op-text'>

<sup>Originally posted by **newtarkprojects** January 13, 2023</sup>
Hello Max,

I have noticed on the server slider, it shows all game servers, even those that have no website name on the servername settings.

Please could it be implemented so that any servers without a website name will not show on the server slider? This will make the server slider look better and hide any test or private servers that are set up on GSA. I have attached the slider from my community website which shows the test server which has no website name in the server settings.

Thank you,
Gem
![image](https://user-images.githubusercontent.com/48177364/212424963-bdbd6751-5f8f-458c-bb90-ec41deac709e.png)

</div>

**Comment by mvaessen** [comment]
Hi @GemGem, are you sure there is no space in the text field on the game server settings page?

**Comment by newtarkprojects** [comment]
Hey Max,

Yeah I will use the test one as an example since it is in the image on my original post. I have a few servers that show in the slider but have no Website name. Do you want the server IDs to help?

Thank you,
Gem

![image](https://user-images.githubusercontent.com/48177364/212426464-0402cbd1-4399-4bca-86bf-9cf05304059f.png)

**Comment by mvaessen** [comment]
hm, weird. Yes, please do!

**Comment by newtarkprojects** [comment]
Hey Max,

No problem. The one in the images is: 15967 / fwsrjqixd

Others: 15973 / nrobpbkfd
16134 / ujxbuvtuk
16144 / fkougjrdn

Do let me know if you need anything else to help.

Thank you,
Gem

**Comment by mvaessen** [comment]
Thanks Gem!
I did a quick check and it does look like something is bugging. I manually changed the value for those 2 servers to quick fix. 

Next weeks update should fix the bug. For the time being I recommend not changing the name or it may show up again.

**Comment by newtarkprojects** [comment]
Amazing work, thank you Max!

**Comment by mvaessen** [comment]
This issue should be fixed now. Please reopen if it comes back!
