### ISSUE TITLE
Patreon Error Gateway Field Required

### ISSUE THREAD

**Issue by likefriendly** [gameserverapp/Platform#328]
**Describe the bug**
Tried connected today GSA with Patreon but after Syncing the Patreon Packs and trying to enable the Suporter Tiers for the Website in GSA I get a constant Error message : "The gateway field is required"

**To Reproduce**
1. Go to Supporter Tier
2. Click on any Supporter Tier and select Settings
3. Try to activate or make any changes

**Expected behavior**
Don't know yet what I should expect because it's still a Beta Function.

**Screenshots**
https://imgur.com/0dipj8K

**Comment by mvaessen** [comment]
Hi,

Thanks for reaching out. Would you mind including a screenshot of the patreon overview page?

**Comment by Sarpendon** [comment]
Just realized used wrong GitHub Account. Sorry for that. 

Anyway here are the Screenshots I hope these are the right ones. 
![Screenshot (393)](https://user-images.githubusercontent.com/76249460/213007914-c5d46a7c-83b6-4a41-b488-132fdeb36c48.png)
![Screenshot (394)](https://user-images.githubusercontent.com/76249460/213007919-e0d569a5-74ae-423d-b966-eb3d0b88c637.png)

**Comment by Sarpendon** [comment]
Just realized logged in with the wrong GitHub Account. 

here are the requested Screenshots I hope they are the right ones: 

<img width="1717" alt="Screenshot (394)" src="https://user-images.githubusercontent.com/76249460/213008319-40e50934-c56c-40f5-8d68-0faa3b25541d.png">
<img width="1718" alt="Screenshot (393)" src="https://user-images.githubusercontent.com/76249460/213008327-145cb8ae-02d0-4681-a648-a5aea9d8e793.png">

**Comment by mvaessen** [comment]
Sorry, I meant the patreon overview page on GSA. The page where you can connect your patreon to gsa

**Comment by Sarpendon** [comment]
No problem mate, here you go. Thanks for your time. 
<img width="1717" alt="Screenshot (395)" src="https://user-images.githubusercontent.com/76249460/213010013-d07495e1-fd6c-4cbf-8e46-4aae54e207e6.png">

**Comment by mvaessen** [comment]
Thanks! To be sure, after connecting your patreon to gsa you created the supporter tiers via GSA's patreon page?

**Comment by Sarpendon** [comment]
ehm I had the Supporter tiers on patreon already so I guess I did it the wrong way around :D ok good to know. That might be the issue. Sorry max to have botherd you with my stupidity.

**Comment by Sarpendon** [comment]
Never Mind Deleted them all and tried again to create the Supporter Tiers via GSA's Patreon Page but same Error pops up.

**Comment by Sarpendon** [comment]
<img width="1290" alt="Screenshot (396)" src="https://user-images.githubusercontent.com/76249460/213014697-95904805-2022-4cb0-af73-faa8956e9469.png">
Clicked on the Create Supporter Tier 

Added Settings and tried to activate it 
<img width="1705" alt="Screenshot (397)" src="https://user-images.githubusercontent.com/76249460/213014795-deaca951-c4b1-47f7-9fcd-a1a94a635f83.png">

**Comment by mvaessen** [comment]
> ehm I had the Supporter tiers on patreon already so I guess I did it the wrong way around :D ok good to know. That might be the issue. Sorry max to have botherd you with my stupidity. 

Yeah that doesnt matter, the system is designed to work with existing patreon tiers.

I'm not sure exactly why the error comes up for you, but i'll check it out and try to include a fix in this weeks update

**Comment by Sarpendon** [comment]
As always you're the best thank you Max

**Comment by mvaessen** [comment]
The problem was resolved and OP was notified via Discord
