### ISSUE TITLE
[ARK S.E.] Dino brush not working

### ISSUE THREAD

**Issue by RageQuitCommunity** [gameserverapp/Platform#333]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
The dino brush doesn't work. 

**To Reproduce**
1. I equip the brush and  hit the dino
2. The window that shows color options appears
3. Selecting colors and regions nothing happens and colours don't change
4. When I apply, the brus is destroyed and the dino is still the same.

I tryed with argentavis and pteranodon without success.

**Expected behavior**
To apply colors to the dino.

**Comment by mvaessen** [comment]
Hi, i just tried and I cannot reproduce the issue. The brush seems to work fine with a fresh game server that only has the GSA mod installed. See screenshot below. I recommend testing with a test game server and see if you can reproduce the issue with just the GSA mod installed. From there you can try adding the mods you had installed until you find which one is causing the paint brush to stop working.

![20230129150214_1](https://user-images.githubusercontent.com/13402423/215331259-aa6195e3-56b0-486f-af38-31eea5bb9595.jpg)

**Comment by RageQuitCommunity** [comment]
I don't know why but it doesn't work for me.
I've just restarted three server, 2 brand new wiped.
![image](https://user-images.githubusercontent.com/123845541/215333361-26f46a29-a8ef-4c4a-87c2-ae47c38fac49.png)

**Comment by mvaessen** [comment]
Can you specify which mods are installed on the server you used to test with?

**Comment by RageQuitCommunity** [comment]
These are the mods we have:
- Structure Plus (S+)
- Awesome Spyglass
- Lethals Reusables
- Human NPCs
- Editable Server UI (WBUI) Open Source
- No Explorer Note XP

I'll try in single player without mods but GSA as you said.

**Comment by RageQuitCommunity** [comment]
In single player, with only GSA mod, it doesn't even open the GUI! I can't hit the dino with the brush (spawned with scriptcommand gsadinocoloring {quantity} {steamid})

**Comment by mvaessen** [comment]
Hi, please use the suggested method in my previous message: 
>  I recommend testing with a test game server and see if you can reproduce the issue with just the GSA mod installed. From there you can try adding the mods you had installed until you find which one is causing the paint brush to stop working.

Stuff may not work in SP, since it's missing many things. If you can reproduce the issue using the steps mentioned above I'm happy to look into it further.

**Comment by RageQuitCommunity** [comment]
Ok, il restart one of my server wiped and without mods but gSA. I'll let you now asap. Thanks!

**Comment by RageQuitCommunity** [comment]
No way. Scorched Earth just wiped with only you mod. It doesn't work.
![image](https://user-images.githubusercontent.com/123845541/215335794-101f22b5-b74d-43aa-b3a1-50f102ee9d41.png)

**Comment by mvaessen** [comment]
Thanks for the update.
I'll ask the devs if they know any reason why it works for me and not for you.

**Comment by RageQuitCommunity** [comment]
Maybe it's a client issue?

**Comment by mvaessen** [comment]
Could be. I'm not a mod dev so I'm not sure. The only difference I notice between your screen and mine is that you're using a different language. This could be relevant, but I honestly doubt it's the client language.

When the devs replied I'll update you here. It might take a couple days.

**Comment by mvaessen** [comment]
Hi, the dev couldn't think of any reason why it wouldn't work.

To be sure, can you please try and select a color for each region **before** hitting "Apply Color"?

Alternatively you may want to try validating your ark client (use Google if you dont know how to do that). 
Hopefully that helps, otherwise we don't know what could be causing the issue.

**Comment by RageQuitCommunity** [comment]
|To be sure, can you please try and select a color for each region before hitting "Apply Color"?|
Already done, in a thousand way and for thousand times :-)

|Alternatively you may want to try validating your ark client (use Google if you dont know how to do that).|
It's not my client, other players tried and all of them have the same issue.

It's a big problem, we really need to solve it because colorizing dino is the most important item I need to put in the store to substain our community.

**Comment by mvaessen** [comment]
Hi, since it works completely fine during my test, for which I used the latest ARK and GSA mod, there isn't anything we can do for you at this point.

I recommend following the previously mentioned steps by the letter, to rule out any external factors. It's most likely related to something you have setup / configured / installed. Otherwise I would have been able to reproduce.

**Comment by RageQuitCommunity** [comment]
I installed a brand new server only with your mods and it doesn't work. What elese I have to do?
I've a premium account to expand to an entire cluster of 12 maps of ark, for what am i paying if your mod doesn't work?
Are you sure that is an incompatibility with italian client?

**Comment by mvaessen** [comment]
Hi, can you make sure to remove any custom configs. Please only use the ModID's to load in the GSA mod and leave everything else out. If that doesn't please try changing your clients language to English to rule out issues there.
The mod dev uses a German client, so I doubt that's relevant.

I don't think Github is the appropriate place to discuss what you're paying for. But if you're in doubt, you can check out the GSA website https://www.gameserverapp.com/ to see all the feature's you're getting. Do note that you're paying to add servers, not to use the mod. The mod is available for free, to everyone.

**Comment by RageQuitCommunity** [comment]
Thanks for have left a customer in a big trouble. Much appreciated.

**Comment by mvaessen** [comment]
Hi, I've tried to help you out but there is only so much I can do. Since this issue seems to drift away from trying to resolve the issue, i'm going to lock the issue. 

As mentioned before: we tested the issue and can't reproduce. Please rule out issues on your end, as it seems to work fine for anyone but your server.
