### ISSUE TITLE
[ARK S.E.] Wrong URL for voting on topgameservers.net - 404 page not found

### ISSUE THREAD

**Issue by RageQuitCommunity** [gameserverapp/Platform#334]
**Describe the bug**
The URL for voting on topgameservers.net is wrong

When you click on voting tab or link generated by discord bot the browser opens this url:
https://topgameservers.net/server/[serverip:port]/vote
and the page is not found with 404 error.

The right url is this:
https://topgameservers.net/ark/server/[serverip:port]/vote

You have just to put "ark" between the domani and /server/.....

It also works without "vote": https://topgameservers.net/ark/server/[serverip:port]*

*I used [serverip:port] to not spam my server ip and port :-)

**Comment by mvaessen** [comment]
Hi, thanks for reporting. This should be fixed now. Please re-open if the vote url is still incorrect.
