### ISSUE TITLE
TopConanServers Changed to TopGameServers/ Invalid API

### ISSUE THREAD

**Issue by Krysez** [gameserverapp/Platform#340]
**Describe the bug**
TopConanServers Changed to TopGameServers and now the Voting API is invalid

**To Reproduce**

1. Go to 'Voting Rewards'
2. Click on 'Settings'
3. The TopConanServers link is now invalid as well as the API. After research I found it was changed to TopGameServers.

**Expected behavior**
Users could click the Vote button on my website and redirect to TopConanServers to vote on the server

![GSA Error](https://user-images.githubusercontent.com/17150924/217022295-7c0774ba-9e01-481a-acce-c04d1cfad077.png)

**Additional context**
It seems all of the same settings are there I think the Link inside the Vote Settings needs to be changed to https://topgameservers.net

**Comment by mvaessen** [comment]
Hi!

Thanks for reporting. I updated the code to work with their new API.

In order to test you may need to remove the API from the field and save before you can add it again and have the API key validated.

Please feel free to update this issue if something isn't working.
