### ISSUE TITLE
Widget twitching

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#344]
I don't know if this is a GSA or my issue. I have my browser windows smaller. My issue appears only when I'm on 50% window size... I got a clip from that :D

https://user-images.githubusercontent.com/99832504/218254685-ffdecec4-907d-440c-91b7-22dd338db6ef.mp4

The browser I'm using: Latest Edge
On Firefox it happens also but on 30 and 40%.. 

Don't know if that's important. Just want to let you know

**Comment by mvaessen** [comment]
Hi, thats an interesting jiggle. Thanks for reporting!

Any particular steps to reproduce? Or does it do that on page load? I admit i didnt test with internet explorer.

**Comment by GERDragon** [comment]
It only happens if I hold CTRL and Scroll down with my mouse wheel.

**Comment by mvaessen** [comment]
Haven't noticed it on Chrome on Windows. Does it only happen when you change the zoom (CTRL+ or CTRL- should be similar to CTRL scroll)?

**Comment by GERDragon** [comment]
Yes, only when I scroll. If I'm in my wanted resolution and press save changes on the top right, the twitching stops even when switching pages back and forth.

**Comment by mvaessen** [comment]
So, on a test i noticed that simply reloading the webpage solves the problem. So going to close
