### ISSUE TITLE
Webhook api not authenticating 

### ISSUE THREAD

**Issue by Kriz02** [gameserverapp/Platform#346]
Have been trying to make use of the webhook api to develop a plugin. No matter which content type I have tried it always returns 404 unauthorized. I have even went to a manual test using postman and still receive the same error.

I am using the correct server id, client id, and including the secret in the body as raw text in the text/plain content type, I have also tried using text/html, text/css, text/xml with no luck. I am wondering if there may be an issue with the API system. 

![Untitled](https://user-images.githubusercontent.com/92939298/218349181-011705a1-9160-4517-bde3-f856f07d3521.png)

Was asked to put this here to see if you/when you have time to look at it.

Thank you.

**Comment by mvaessen** [comment]
Hi,

Just tested and it seems to work alright. Do note that you can only control the servers for the dashboard that you got the API keys from. a `401` error suggests you're trying to control a server that isn't available for your API keys.

![Postman_and_Webhook_API_-_Support_-_GameServerApp_com](https://user-images.githubusercontent.com/13402423/218420837-8cace46c-484b-48e4-b20e-b386686ee4b0.jpg)

**Comment by Kriz02** [comment]
Thank you for looking into it, for whatever reason it is working today, did not change anything, just hit "Send"

![Untitled](https://user-images.githubusercontent.com/92939298/218470502-5dcf3eee-d67d-4b53-be69-660b2d10a92a.png)

**Comment by mvaessen** [comment]
Hi, glad it's working now. Nothing changed on GSA's end either.

**Comment by Kriz02** [comment]
Sometimes the world is just against you I suppose... Even the plugin is working now, so all is well that ends well I suppose. Sorry for taking time away from your other projects.
