### ISSUE TITLE
Incorrect "Author" name for "ArkServerApi" installation page.

### ISSUE THREAD

**Issue by GameServersHub** [gameserverapp/Platform#349]
![image](https://user-images.githubusercontent.com/87217476/219880749-534f5212-43bd-4476-b89e-fa7bc0540481.png)

**Describe the bug**
The author's name is outdated and not up to date. It should be "**[GameServersHub](https://gameservershub.com/forums/resources/ark-server-api.12/)**" Michidu has resigned and retired he no longer does updates for the ArkServerApi framework the updated framework is run by the new development team and is located at: https://github.com/ServersHub

**Comment by mvaessen** [comment]
Hi,

Thanks for reporting!

I wasn't aware that the ARK server API plugin was still showing an author.
In the next update the author will be removed for frameworks that still have an author listed, so I don't have to update it in the future anymore.
