### ISSUE TITLE
Sales & Coupons

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#358]
### Discussed in https://github.com/gameserverapp/Platform/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **AbdelTM** March  1, 2022</sup>
Add a feature to creates like for spring sales, black friday sales, etc. And coupons to give discounts</div>

**Comment by exodusogark** [comment]
Add a feature to have a discount automatically activate when the monthly sales goal is met. I like to reward my players with 50% reward shop items to the end of the month when they hit that monthly donation goal. Would be nice to be able to setup a reoccurring discount that automatically activated when this goal is met.
