### ISSUE TITLE
Visual monthly stripe bug

### ISSUE THREAD

**Issue by JXYZP-G** [gameserverapp/Platform#362]
When having a monthly payment with stripe and the support tier is activated it still shows hidden on the dashboard. But they just work fine.

![image](https://user-images.githubusercontent.com/43095469/223563080-307f08b7-0064-4b7a-af20-de1ef5cdcf1d.png)

![image](https://user-images.githubusercontent.com/43095469/223563125-3d1e3b14-3f7d-4baa-8ffe-32fe130fbf62.png)

![image](https://user-images.githubusercontent.com/43095469/223563651-cf4c9468-eecd-4ed7-97b0-15f7a12df562.png)

**Comment by mvaessen** [comment]
Hi,

Thanks for reporting! This should be fixed in the upcoming release
