### ISSUE TITLE
Achievement For Gameplay Time Not Registering Server

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#363]
So while attempting to set up an Achievement task that would send tokens to a player that has accrued an hour of gameplay time, I've noticed some things that might be possible bugs. Here is the config below: 
![image](https://user-images.githubusercontent.com/44717221/223932630-b5f9c17d-a1d2-4d71-a3d3-a649491b08fa.png)

Since activating the Achievement, it activated for all of the players that were online at the time, but it would not detect their character, nor the game server it registered on. I was concerned because the second half of this task is to deliver a notification in-game through a chat plugin. 

![image](https://user-images.githubusercontent.com/44717221/223933092-7e662d17-680d-4bbe-b0aa-22a8eef0b071.png)
![image](https://user-images.githubusercontent.com/44717221/223934382-07a26e99-8582-48b3-8b58-7cf73a702a77.png)

Checking the log entry on the Achievement indicates that it wasn't able to find the server that the player was logged in on. 

![image](https://user-images.githubusercontent.com/44717221/223933272-e301bc28-c67b-46a6-92d1-5fb1ad43cddc.png)

However, checking the admin/dashboard log and the website transaction logs confirms that the player received the tokens. 
![image](https://user-images.githubusercontent.com/44717221/223934149-dd3f80bf-8814-4d27-bc58-6aa384f44b1b.png)
![image](https://user-images.githubusercontent.com/44717221/223934129-1700baaf-293f-4bfb-b7dc-5cf1611d253f.png)

So even if the tokens are successfully being sent every logged hour of gameplay, I'm concerned about the servers themselves not getting registered, especially if it the constant failures of the tasks make it possible for the task to get disabled.

**Comment by mvaessen** [comment]
Hi, thanks for the detailed report!
I'll try to reproduce the issue and see if I can include an update on the upcoming release

**Comment by Decollates** [comment]
Interesting, thank you for taking a look!

Would it still be possible to target the character in the server and deliver a notification when they receive tokens? I know the GSA integration mod has its own pop-up balloon/chat notification, but I would like to keep with the “brand” of my server with its notifications.

**Comment by mvaessen** [comment]
with the current options that isn't possible unfortunately. For that we need other Achievements for characters.
So something like `Character is online for [X] hours` would allow for what you're trying to do.

I can't give an ETA atm, but i'll try to add this soon (tm)

**Comment by Decollates** [comment]
Okay, that’d be great if the system could track player data and character data, but still deliver messages (or at least target characters) to the character. I just got the email that the Achievement task has been disabled… 😵‍💫

**Comment by mvaessen** [comment]
Upon further talks on Discord did it became clear to me that folks want:
a single achievement that has sub-goals /progress, where it will re-reward the player involved for every X hours they recorded on the player stats.

This is already possible with the current feature set, but it requires people to create a separate achievement for every hour, so: 1, 2, 3, 4, 5, 6, 700,701,702 etc.

Since this is fairly unworkable, do we need some sort of new achievement type, which can track progress. Where the main achievement has sub-achievements / progress that get recorded.

**Comment by mvaessen** [comment]
Created a new suggestion for this: #875
