### ISSUE TITLE
Editing Shop Pack Collections with lots of Sub Pack Causing Issues with Randomizer

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#364]
One of my admins was editing the "thank you" message for a shop pack (a secondary rcon command that sends a chat message to the player's character) in our largest shop pack collection, one for all Ark Land tames. After saving, it affected every single sub-pack, as if it had "cloned" the text command to every other pack. If you refresh the page after this, it fixes itself. 

It also is not registering that "total randomizer options should be 100%" when the settings are being copied over and legitimately set up to equal 100%. 

https://user-images.githubusercontent.com/44717221/224461377-2d325b94-e76d-4a9d-bb45-78eceeae26a9.mp4

**Comment by mvaessen** [comment]
Hi,

I tried watching the video but I found it very hard to understand what was going on.

Could you please type out steps to reproduce this issue?

Also, please make sure that the total chance for all items combined amounts to 100%. This often is not the case when people reach out.

**Comment by Decollates** [comment]
You can close this now; it looks like things have stabilized for the admin in question.
