### ISSUE TITLE
Global schedule countdowns

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#372]
### Discussed in https://github.com/gameserverapp/Platform/discussions/262

<div type='discussions-op-text'>

<sup>Originally posted by **GERDragon** August 19, 2022</sup>
Add an option to set global countdown timers, for things like restarts, shutdown etc.
This allows people to set a default countdown, while still having the option to override this custom setting per game server.</div>

**Comment by GERDragon** [comment]
Addition: Having the option to set the time for Restarts/Shutdowns from standard 5 minute countdown to whatever we prefer but keeping 5 minutes at standard as a safety feature :D

**Comment by mvaessen** [comment]
> Addition: Having the option to set the time for Restarts/Shutdowns from standard 5 minute countdown to whatever we prefer but keeping 5 minutes at standard as a safety feature :D

Note2self: this is about scheduled action modals
