### ISSUE TITLE
Plugins are not updating.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#385]
At least some plugins are failing to update but claiming to be updated.

Items+ is one I tested with. I believe lethal's decay is having the same issue but not 100% positive.

Steps to reproduce.

Shut down server. (10547 / mxpowadhp ) was the one I tested on.

Click actions on items + > update plugin.
Result. 
![image](https://user-images.githubusercontent.com/749937/226789877-26b24bd5-a5e8-4341-897e-aa930a7d5706.png)

Plugin now shows as updated to 3.0

Issue. Actual plugin files were not updated. 

![image](https://user-images.githubusercontent.com/749937/226790029-7ab48c40-a29b-4471-be22-0482446b4b71.png)

Note the file modification dates. Top is the server after "updating". Bottom is the proper 3.0 files.

Next step. Move to a server that has never had items+ installed on it. (16170 / kmjpwbdfx)
Install api and items +
![image](https://user-images.githubusercontent.com/749937/226791322-5afcc0cd-25c5-4a15-8ba7-c4014037f26a.png)
Note that this one has the correct recent dates for the plugin files.

If you need to test 16198 / izgrhmevn can be used to test all you want. It still shows as being on the older plugin.

**Comment by mvaessen** [comment]
Thanks for reporting!

I think this was caused by the `Expand-Archive` command, to unzip. Previously it had no problem overwriting files, but I guess an update changed that.

Tested on your test server, and as far as I can tell is it updating properly now. 

Can you please check and report back whether the issue was resolved?

**Comment by birdman3131** [comment]
So it is now working.

What does this mean for servers that "updated" but failed? I know which ones of mine are messed up and will update them manually but I find myself believing that there may be many GSA customers in the same boat.

Not sure if all plugins have a plugininfo.json file with the version number in it but I think all the ones I have looked at do. Might be worth doing a sanity check using that.

I will say doing a server update does not fix the issue on a server that is improperly reported as updated.
