### ISSUE TITLE
Unreadable characters in logs, chat and discord

### ISSUE THREAD

**Issue by KissmanCZ** [gameserverapp/Platform#387]
**Describe the bug**
I am not sure if this is GSA or server (RUST) issue. I can see proper characters in player list... for example:
<img width="141" alt="image" src="https://user-images.githubusercontent.com/13331823/227043401-4d85d960-ab84-41a8-a3ca-fe6f8d5518a8.png">

but character name is not correct:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/13331823/227043506-b5f9290d-9d5e-4f06-b6cc-a75af2ba97e6.png">

and also name in chat is wrong:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/13331823/227043618-a49cd3be-7e99-47fd-8a42-98081937a800.png">

and name on Discord too:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/13331823/227043739-c0509c89-ada2-4b88-81e5-ba8dab8519b1.png">

I am using Ubuntu 22 LTS, server locale is set to en_US.UTF-8 UTF8.

**Comment by mvaessen** [comment]
Hi,

This is a common thing for games like ARK, where their RCON system does not support special characters.
Can you please post a link to their character page, on your dashboard, so I can see the information about the character?

**Comment by mvaessen** [comment]
I've made some changes and all character names should now show proper UTF8 encoded names
