### ISSUE TITLE
Survivor instead of in-game name - DayZ

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#393]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
For players that connect to a server on DayZ, their Character gets the name "Survivor" instead of their set in-game character name

**To Reproduce**
1. Have a DayZ Server
2. Connect to it
3. Check if the player shows up on GSA webpage
4. Check what name was given to the player

**Expected behavior**
The in-Game character name should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/99832504/227946925-8863373e-e346-4b61-a251-67af14fd6f79.png)

Testing this with more players later

**Comment by LimitlessDrag0n** [comment]
I have more players joining daily :D All called survivor. Any eta?
![Survivor](https://user-images.githubusercontent.com/99832504/229348646-e5dab94f-c196-47bc-9d5c-f981a760980f.png)

**Comment by mvaessen** [comment]
Hi,

This should be fixed now. Please note that due to how DayZ has this setup, player names will only get picked up when the player is actually online. So existing players with the name `Survivor` will not update to anything else unless they come online.

**Comment by LimitlessDrag0n** [comment]
Yes, works as intended! Tested it with my account. Is (Lobby) behind the name intended?

![image](https://user-images.githubusercontent.com/99832504/229500179-4292fbb7-5d01-4cd4-bb54-3a44e2a463ac.png)

**Comment by mvaessen** [comment]
Hi, that is probably added by DayZ. I added some code to remove that if it's there.
