### ISSUE TITLE
Dedicated Connect Event Error -  Could not download character file. Make sure FTP is working properly!

### ISSUE THREAD

**Issue by Nytridr** [gameserverapp/Platform#395]
Could not download character file. Make sure FTP is working properly!

happening on all the Dedicated connect servers maps when people log on.  

Able to log in and download files via info from connect screen on server.  17356, 17362, +

When people log on this spams the event error log.  When they log off the error goes away.  It will time out and stop for a little bit.  Every so often it will say that its reachable.

Also on discord the welcome part for users login on says they disconnected and then reconnected.  Not sure if this is part of the same issue or not.

To reproduce, just watch the event screen when someone is logged on.

![image](https://user-images.githubusercontent.com/31319495/228690127-32bdc82c-ecc0-4088-9067-2245bf31806b.png)

**Comment by mvaessen** [comment]
Hi, i've added some extra debugging info to see what error is generated.

**Comment by Nytridr** [comment]
Test server is now up and running.   17382   This one is doing it also.. It only has 1 mod on  there so should be a lot faster connecting to instead of 38 mods.. I am currently on right now just idling, so if you want to check things out.

**Comment by Nytridr** [comment]
okay this one was on me, from a very long time ago.  Have a simple script that runs during install of the OS that way I do not have to worry about me not being able to connect to things from remote.  

Thank you for your help.
#pasv_address=98.21.82.119

pasv_addr_resoulve=YES
pasv_address=cosmicknights.net

The script had a spelling error and I never even noticed it until now, which explains an issue I am also having on another private server.  

The new changes have been put in and it is now working like intended on my private server and this one now.. 

#pasv_address=98.21.82.119

pasv_addr_resolve=YES
pasv_address=cosmicknights.net

**Comment by mvaessen** [comment]
Okido, to be sure; is the problem resolved now?

**Comment by Nytridr** [comment]
Seems to be fixed.  No errors for the last 30'ish minutes.  Thank you both for your help.
