### ISSUE TITLE
Configs not written to .cfg - DayZ

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#399]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Changing some settings in our default config wont be added to server

**To Reproduce**
1. Go to Config template
2. Change motd to a message you want
3. save and check if on server after restart

**Expected behavior**
That, when I change settings, that they're corectly importet.

**Screenshots**
No Screenshot but my format of serverdz.cfg, maybe there is the issue
[serverdz.txt](https://github.com/gameserverapp/Platform/files/11132253/serverdz.txt)

I keep them like that because its easy to see what is what and even the // are a good help

**Comment by mvaessen** [comment]
Hi,

Thanks for reporting. This should be supported now.

Please let me know if it's working now

**Comment by LimitlessDrag0n** [comment]
Worked as far as I can see. If something is still missing, I'll let you know, but the issue is resolved for this
