### ISSUE TITLE
Server Disconnection error we were discussing on discord

### ISSUE THREAD

**Issue by Nytridr** [gameserverapp/Platform#401]
![image5](https://user-images.githubusercontent.com/31319495/229652719-2e97a774-176b-4213-b687-ba413c32fb7f.png)
![image4](https://user-images.githubusercontent.com/31319495/229652722-11cef361-18f0-432b-9f91-59d52cf494fa.png)
![image3](https://user-images.githubusercontent.com/31319495/229652723-198cd643-47a3-461e-9289-44ae626fc311.png)
![image2](https://user-images.githubusercontent.com/31319495/229652724-3541d45f-57d4-4ff3-9fb7-c56ebdedb65b.png)
![image1](https://user-images.githubusercontent.com/31319495/229652725-0a62c4b0-e34f-4754-9ef9-55e8580c82f9.png)
![image](https://user-images.githubusercontent.com/31319495/229652728-5d711e5f-2636-42f8-93aa-3aa6db58b217.png)
![image6](https://user-images.githubusercontent.com/31319495/229652730-e7d87cc9-d3d9-4004-a1ff-db587524dca0.png)

Machine  921 / 935
98.21.82.119

**Comment by mvaessen** [comment]
Hi,

I tried connecting to the FTP credentials for the Crystal server, but i wasnt able to connect.
While this is unrelated to the reported issue, the Events log if full of errors with that. Please resolve that first.

**Comment by mvaessen** [comment]
Hi, im closing this issue because it's most likely resolved based on your message on Discord.
