### ISSUE TITLE
"Get Tokens" community website page not linking to right page. 

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#406]
Website player profile link to "get tokens" under the Tokens tab leads to the paid Supporters webpage, not any established dedicated page that actually lists the shop packs for buying tokens (like what had been recently updated for the Ark in-game shop UI). 

https://i.gyazo.com/e685d714eaf140cd10849f4d81aac5c2.mp4

**Comment by mvaessen** [comment]
Thanks for reporting!

Some time ago I added this option to the integration mod settings page, but didn't consider that we should also add this to the community website. 

So I relocated the option to set a custom token page from the Integration mod section to the **Website settings page**. Now you can set a custom page there, which will automatically configure the right URL on the mod and the community website.

If you already had a custom link setup, this should automatically apply to your community website now too.
