### ISSUE TITLE
New Modfolder name for mpmissions - DayZ

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#415]
__Please make sure to leave out any sensitive information__!

**Describe the issue**
A new folder was found for DayZ (MPMissions)

Offline

**Section**
DayZ Server Configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/99832504/232205642-aa0edb5a-a74d-4e09-93d8-113e34c45130.png)

**Additional context**
Addition to https://discord.com/channels/315049169071112193/1075802591377768478/1092804707858251837

**Comment by mvaessen** [comment]
Done! thanks for reporting
