### ISSUE TITLE
GSA Admins not able to delete groups

### ISSUE THREAD

**Issue by Ian-Highlander** [gameserverapp/Platform#416]
Raising on here as requested in Discord:

Hi Max, minor issue and may be something I've missed in the configs, but I have an additional admin who's unable to delete groups (Ark Tribes) from the GSA dashboard despite him being a member of an admin group that has the permission to do so. He can however delete characters and the only permission I can find appears to be for both.

![image](https://user-images.githubusercontent.com/109648228/232211727-08772cac-9cdd-4cd6-9ec4-8a106c318088.png)
![image](https://user-images.githubusercontent.com/109648228/232211808-4de11e9e-a0ba-45de-867c-ee6ee5c50f37.png)

**Comment by mvaessen** [comment]
Hi Ian,

Nice catch! That was a bug indeed. 
Should be fixed now. Please let me know if your admins still cant remove a tribe.
