### ISSUE TITLE
Wrong information about available slots for install a new game server

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#423]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Wrong information about how many servers are available for install

**To Reproduce**
1. Go to "Install a game server"
2. on the top right, you see how many you can install with your current plan
3. Scroll down to what machine you want to install your game server on 
4. See different numbers

**Screenshots**
![image](https://user-images.githubusercontent.com/99832504/234014745-88ce1d9c-cadb-48fc-bee2-5fc778c87614.png)

![image](https://user-images.githubusercontent.com/99832504/234014795-19c4ccb3-676f-4a16-9523-b42decfddfcc.png)

![image](https://user-images.githubusercontent.com/99832504/234015183-fc354b6c-17d7-40b6-a018-02867dcc7c4c.png)

**Additional context**

**Comment by mvaessen** [comment]
Hi,

Thanks for reporting.

Those 2 numbers reference to different things. There is a hard-limit of 80 containers per machine. Which is the `x/80` you see. The other number refers to your add-on limit
