### ISSUE TITLE
Pagination issue in the in-game shop.

### ISSUE THREAD

**Issue by Ian-Highlander** [gameserverapp/Platform#427]
Small bug in the in-game shop interface (Ark). Once you get to 19 pages of items (we're at 23 pages now), you can't select past it (in-fact the right side of the 19 is clipped off. It's probably just a scaling issue and we get round it by using filters for everything but would be good if it could be resolved.

![image](https://user-images.githubusercontent.com/109648228/235360793-196996d5-e98b-4010-8990-b5f427d50997.png)

**Comment by mvaessen** [comment]
Small update:

- checked the API and unfortunately this cant be solved without the mod team
- mod team will take a look shortly to see whether this can be solved easily.

Proposed solution:
![image](https://github.com/gameserverapp/Platform/assets/13402423/7ded009b-a4d5-412d-a36f-81f1ac01fcf0)

**Comment by birdman3131** [comment]
I would also propose a number entry box along with the examples listed.

**Comment by mvaessen** [comment]
After discussing further with the mod team we're now planning to make the pagination scrollable, as this is the easiest thing to do without changing anything that might cause unwanted issues.

Hopefully somewhere this week we'll get the first test version.

**Comment by mvaessen** [comment]
hi @Ian-Highlander, the mod was updated and it should now have a scrollbar when there are many pages. Please let me know whether this fixes the problem or whether it's still causing issues.

**Comment by Ian-Highlander** [comment]
> hi @Ian-Highlander, the mod was updated and it should now have a scrollbar when there are many pages. Please let me know whether this fixes the problem or whether it's still causing issues.

Confirmed, working like a charm, thanks Max
![Uploading image.png…]()
