### ISSUE TITLE
Claim vote Banner / Button

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#448]
### Discussed in https://github.com/gameserverapp/Platform/discussions/444

<div type='discussions-op-text'>

<sup>Originally posted by **Toneeno** May 23, 2023</sup>
You should add a better claim vote system.
Would be nice to have like a button to claim a vote that could be posted on the webpage wherever you want like content,
in this way users could create Claim Vote pages.

Could be better to add a vote button too (as webpage content) to create a dedicated page where users can vote and claim easy it right after.</div>

**Comment by Toneeno** [comment]
Oh, thanks for considering this topic as an important feature for GSA.

I would like to suggest adding another feature that comes to mind. Perhaps you can include a "Claim" button and a "Vote" button directly in the ARK F3 shop as well, so that people don't have to switch between the website and the game. This would likely encourage players to use the vote and claim features more frequently.

**Comment by mvaessen** [comment]
> Oh, thanks for considering this topic as an important feature for GSA.
> 
> I would like to suggest adding another feature that comes to mind. Perhaps you can include a "Claim" button and a "Vote" button directly in the ARK F3 shop as well, so that people don't have to switch between the website and the game. This would likely encourage players to use the vote and claim features more frequently.

Hi, for new suggestions please open a new suggestion in the appropriate section. You can use tasks to create in-game commands for vote claiming

**Comment by mvaessen** [comment]
Hi,

Upon further investigation did I came across some things that need to be changed before this suggestion can be implemented. At this moment claiming happens per server, so adding a claim button would require to select a server too. This means that for people with multiple servers, you need multiple buttons. 

A better solution has to be found to work with this, without causing too much load for voting sites when customers have 20 game servers (basically resulting in 100 requests in a matter of seconds).
