### ISSUE TITLE
Epic Crossplay needs cert on windows.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#477]
So using the same config settings I am able to join a epic server hosted on linux (Ubuntu 22.04 ) and not one hosted on windows (2022)

According to https://discord.com/channels/278678986673094656/278678986673094656/1109188067782299660 in the server admin discord.

![image](https://github.com/gameserverapp/Platform/assets/749937/e4bd1589-c513-4260-a921-24dc6f571a67)

My current assumption is that it is the issue although I was never able to figure out how to install it as I believe the certificate needs to be added during the docker file build process.

**Comment by mvaessen** [comment]
Hi, thanks for the report!

The certificate is now automatically installed upon creating the docker image. 
If the game server was already installed, you will need to recreate the docker image. For that, make sure to follow these steps:

- Shutdown all ARK servers
- Login via RDP
- Open Powershell
- Run `docker image ls`
- Find the `ID` for the image named "gameserverapp-ark"
- Run `docker image rm {ID} --force` (replace `{ID}` with the image id you got from the previous step)
- Then start __one__ ARK server and wait for it to start up completely
