### ISSUE TITLE
Servers should keep their state regardless of updates

### ISSUE THREAD

**Issue by dagbs** [gameserverapp/Platform#485]
All Ark servers, except for one, were stopped (offline). After waking up, we noticed another server online. Going to the dashboard, we can see all of the Ark servers starting. The only thing we can assume happened is an auto-update occurred across all Ark servers; causing them to start after their update.

Can auto-update either wait until the server is manually started or stop once the auto-update is complete?

**Comment by mvaessen** [comment]
Hi,

Auto updates don't start a server when it's offline. In fact, offline servers aren't automatically updated. Best to check the activity logs.

Please don't open issues based on assumptions. That's not what it's for.
