### ISSUE TITLE
DayZ: Servername do not like "&"

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#486]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I have my server named: WIP [CoG] NEFARIOUS Chernarus EU | PVP & Quests & more
comes out on the dashboard like following: WIP [CoG] NEFARIOUS Chernarus EU | PVP &amp; Quests &amp; more

on a widget however: 
![image](https://github.com/gameserverapp/Platform/assets/99832504/7fe2b519-bb84-4667-97c2-cad5afdb434e)

Don't know how it looks on the server overview because name is to long to be shown, and no tooltip is opening up :D

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/99832504/b5c2e390-64a8-4746-b41f-a0cc213062d0)

**Comment by birdman3131** [comment]
This is also happening on a conan server. I save it as "C&T Conan" and it changes to "C&amp;T Conan" 

(Looked close enough to add to this one rather than create a new one.)

**Comment by mvaessen** [comment]
Hi both, this should now be solved. If you come across any sections where this issue shows up (HTML characters being printed as HTML) please let me know

**Comment by LimitlessDrag0n** [comment]
![image](https://github.com/gameserverapp/Platform/assets/99832504/846c6d80-5b85-4200-b9f7-4ddb0f96a9c0)

In the Serveroverview the '&' is right but on the cluster overview 

![image](https://github.com/gameserverapp/Platform/assets/99832504/b9f5422c-b577-4a8d-8f48-035729058fdf)
 but on grid view 
 
 
![image](https://github.com/gameserverapp/Platform/assets/99832504/9f215403-484a-47ce-be22-24c05374c75a)

Maybe I point it out

**Comment by mvaessen** [comment]
Thanks! should be fixed in the next big release 👍
