### ISSUE TITLE
GSA Server Status Card

### ISSUE THREAD

**Issue by ImKomplex** [gameserverapp/Platform#49]
Server Status Cards are reposting new Cards as well as auto Updating the old cards.

I tried deleting the new Cards and it still keeps reposting them.

**Comment by mvaessen** [comment]
Hi, can you please provide more information to help understand what is happening?

**Comment by elusive-ttv** [comment]
I may be able to help clarify, as I noticed the same thing happening in our server. The server status cards are reposting periodically, but leaving the old card in the status channel. The old cards show as offline or something of the sort, which is slightly misleading when a new card for the same server has been posted and is showing the correct status. I don't have any screenshots of this, I clean it up when it happens, but next time it happens I will be sure to screenshot and post here.

**Comment by mvaessen** [comment]
Awesome, thanks for the info @elusive-ttv. Looking forward to your screenshot 👍

**Comment by ImKomplex** [comment]
<img width="552" alt="example 1" src="https://user-images.githubusercontent.com/100098296/156945084-65270b41-a530-486e-8b83-6a1593d54d0c.PNG">
Here is a screenshot you have been asking about. my bad for not seeing the replies

**Comment by mvaessen** [comment]
@ImKomplex thanks. I dont immediately see something wrong on your screen. Can you post a screen where it show the old and the new card? If possible in the same screen.

**Comment by ImKomplex** [comment]
where the line that says March 6th is where the new ones start. above the line are the old ones

**Comment by mvaessen** [comment]
On your screenshot I'm seeing up-to-date timetamps (today at X PM). Can you please provide a screens where the screen shows me the message you refer to along with the new message?

**Comment by ImKomplex** [comment]
![Screenshot_20220307-032256_Discord](https://user-images.githubusercontent.com/100098296/157003494-0a9b4295-c476-4144-8e3b-5ff548c58153.jpg)
Hope this better helps show it

**Comment by mvaessen** [comment]
thank you

**Comment by ImKomplex** [comment]
Np, couldn't take a long screen shot from my PC

**Comment by mvaessen** [comment]
There still seem to be some issues with individual servers, re-posting the status card. See #123

**Comment by nytraven** [comment]
I reset my discord card channel on 1/30 after they were supposedly fixed.   A new set was created on 2/13 and again on 2/27.  Now, today, they have been spamming card sets since 5:47am PDT.  Like every time it is supposed to update the same card, it's adding new ones... the channel scrolls a ton now.  This is even happening for Ark map servers that have 0 players and no players are transferring to or from them.  If this isn't resolved soon, I'll just have to disable the feature.  I really miss the old status log feed.

**Comment by meza** [comment]
Same with `12748 / xzhtijegc` for me #123

**Comment by elusive-ttv** [comment]
We had a couple of ours do it the other day as well, they spammed every few mins for ours. Deleted them all and they've been okay for the past couple of days.

**Comment by mvaessen** [comment]
thanks for the extra info all!

i've noticed that discord's API is inconsistent and uses different kind of names, depending on what webserver (API) GSA is communicating with, at the time. Tomorrows update should fix that. Hopefully this will resolve the problem permanently.

**Comment by ImKomplex** [comment]
the status cards just resent again

**Comment by mvaessen** [comment]
In order to take a serious look into reports i need more info. Please provide useful info

**Comment by ImKomplex** [comment]
Idk what more info you want. It's the exact same thing that's been reported. New status cards are being sent in the discord.

**Comment by elusive-ttv** [comment]
![image](https://user-images.githubusercontent.com/100104764/159265689-e6e4a174-8fac-4cb9-b600-1ca68e0185f8.jpeg)![image](https://user-images.githubusercontent.com/100104764/159265714-2036c31e-67fd-438b-b5d7-be64ad38ddac.jpeg)

I can't get them both in one screen (darn phone) but here you can see one was posted 3/7 and one reposted today. Hope this helps. <3

**Comment by mvaessen** [comment]
thanks @elusive-ttv! I've added some debugging stuff to see what is going on.
Based on the reports it seems to happen to certain status cards only. Does it occassionally create a new card for particular servers, or does it keep posting new ones?

**Comment by elusive-ttv** [comment]
It only happens occasionally, but once it reposted new cards for 2 servers every 3 mins for over 4 hours.

**Comment by ImKomplex** [comment]
For me, every now and then it reports ALL of my server status cards. And when it's done posting all it stops.

**Comment by ImKomplex** [comment]
What info would you like if it does happen again?

**Comment by mvaessen** [comment]
screenshots of old and new card, preferably in 1 screen. Along with as much info like at what interval, whether it affects all or particular cards etc etc.

**Comment by ImKomplex** [comment]
![Screenshot_20220403-185400_Discord](https://user-images.githubusercontent.com/100098296/161455295-5d256845-045d-43a7-8b3d-f0a8793fc838.jpg)
Server Status Cards Just repeated themselves again.
