### ISSUE TITLE
Problem with Sheduled Task

### ISSUE THREAD

**Issue by vipersitoh** [gameserverapp/Platform#50]
**Describe the bug**
I have a scheduled task that changes the template of my ARK server on Sunday at 00:00 but it was activated on Saturday at 00:00

**Expected behavior**
Activate the task at the scheduled time

**Screenshots**
(https://user-images.githubusercontent.com/100100650/154870184-1cd9aa8b-c3f6-4d9d-96ed-1b53e6cb2245.png)

**Comment by mvaessen** [comment]
Hi, based on the provided information it appears as expected to me.

Your screenshot shows that it should run every Sunday. And February 20th was a Sunday.
