### ISSUE TITLE
Help link broken.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#508]
![image](https://github.com/gameserverapp/Platform/assets/749937/ce4ef848-9ceb-4f26-ab13-767fd844c319)

The help link in the dashboard footer is broken. It does nothing when you click on it. It has a link and you can right click and open in new tab but clicking normally does nothing.

**Comment by mvaessen** [comment]
Good catch, thanks for the report!
Should be fixed now

**Comment by birdman3131** [comment]
No problem. I noticed it over the weekend on mobile but wanted to doublecheck it was not just my phone acting up.
