### ISSUE TITLE
Discord customisable messages being ignored

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#541]
Option for users to override `Updating in X` dont seem to be using customisable logic anymore.

![image](https://github.com/gameserverapp/Platform/assets/13402423/5b9f390b-e775-4d96-871b-6044dc2ea37f)

`CustomisableSystemMessage` does not seem to be used.

https://discord.com/channels/315049169071112193/1166795937453199410/1168991168957268108

**Comment by PR3SIDENT** [comment]
I've also created feedback request: https://github.com/gameserverapp/Platform/discussions/542

To decouple the Discord Message customization from the Integration Mod's broadcast settings.

**Comment by mvaessen** [comment]
Note 2 self: also see #552

https://discord.com/channels/315049169071112193/424240875732860929/1170121351743418378

**Comment by mvaessen** [comment]
note 2 self:
-`ContainerNotify` -> `discordStatusLog` -> `DiscordMessage::statusLog`
- other messages work because they are send as broadcasts

**Comment by mvaessen** [comment]
after further investigation i found that this is caused by 2 separate things going on at the same time:
1. GSA forwards all broadcasts (in-game countdown) to discord. The in-game messages __do__ use the customisable messages.
2. The non-translated messages are coming from the discord `status log` feature, which doesn't currently have any customisation options.

Created a suggestion for this #781
