### ISSUE TITLE
Cant select Discord Channels for the Bot Messages

### ISSUE THREAD

**Issue by Deep33** [gameserverapp/Platform#548]
**Describe the bug**
After adding the Discord bot to my Discord, I can't select any channels in the dropdown boxes on the gameserverapp page under the Discord settings.

**Expected behavior**
It should display the channels of my Discord in the settings on the GSA page

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/5716365/89f53d51-de72-45bd-830d-9d4fe9b3368b)

**Comment by mvaessen** [comment]
Resolved, turned out to be caused by not reading what error GSA spit out.
