### ISSUE TITLE
Machine memory for dashboards is incorrect.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#560]
When adding the machine memory to a dashboard graph it does not report correctly.

![image](https://github.com/gameserverapp/Platform/assets/749937/3a34a8de-dfe7-48c0-b26b-d0b289eb34d6)

vs

![image](https://github.com/gameserverapp/Platform/assets/749937/1bcf564b-c2fe-4999-a162-da74c8afd57c)

![image](https://github.com/gameserverapp/Platform/assets/749937/61bcf4da-7c39-4909-9b14-e5a4c8ad7dc4)
 Settings for the purple line. You get the same result if you choose not to specify a machine or server.

**Comment by mvaessen** [comment]
When looking closer this time, i noticed this is a user error. The data set is `game server memory usage`, which lets you select all game servers on a machine (the filter used).

So the memory usage that was logged is only related to the memory usage of the game server that was present on the machine. Based on the memory usage I assume a bit more was running on the machine.

--

In addition am I currently working on a Machine stats dataset, which will let you see the reported memory usage for the entire machine

**Comment by birdman3131** [comment]
So the machine in question had 12-18 game servers running on it at the time. (Been a while since then but we have been running 12+ servers since gen 2). Other than GSA essentially nothing is using memory.

**Comment by mvaessen** [comment]
yep, you're right. It's a bug :D

![Screenshot 2024-02-19 at 21 19 53](https://github.com/gameserverapp/Platform/assets/13402423/0e807b49-cf69-45c2-9716-5f8ac4be0d70)

**Comment by mvaessen** [comment]
Unrelated to the original post:
Options to see graphs for `machine cpu load`, `machine memory used` and `machine disk used` are now available and recording data.
