### ISSUE TITLE
ASA - mod search engine does not find the name of the mod

### ISSUE THREAD

**Issue by ssiwm** [gameserverapp/Platform#565]
the search engine does not find the name of the mod, but searching by mod ID works

<img width="1186" alt="bug1" src="https://github.com/gameserverapp/Platform/assets/105603502/77686a76-4a5b-4324-b387-18f46aec9a23">
<img width="667" alt="bug" src="https://github.com/gameserverapp/Platform/assets/105603502/44c69308-7144-4912-b8b5-84e6344d13ed">
<img width="618" alt="bug2" src="https://github.com/gameserverapp/Platform/assets/105603502/4d0949e0-fefc-4579-b89e-aab930af5dfc">

**Comment by mvaessen** [comment]
Thanks for reporting! This is now resolved
