### ISSUE TITLE
DayZ: Launchparams

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#573]
I want to add more logging to my servers, therefore we need to set some launch params

- dologs
- adminlog

for example

Would be nice to see sometime so I can use the logs for a bot :D

**Comment by mvaessen** [comment]
Hi, for your info, these are already active for Dayz. These are the params GSA automatically sets for all Dayz servers: ` -doLogs -adminLog -freezeCheck`

Are there any other parameters, that are not on the list, that you think should be added?

**Comment by LimitlessDrag0n** [comment]
https://community.bistudio.com/wiki/DayZ:Server_Configuration

Those are all launch params out of their wiki; For me, mainly the logs are important but can be for others 

Launch Parameters
Run the DayZServer_x64.exe via the batch file, shortcut with parameters or other options.

Supported parameters:

-config=serverDZ.cfg - Selects the Server Config File
-port=2302 - Port to have dedicated server listen on
-profiles=C:\Users\%USER%\Documents\DayZServer – Path to the folder containing server profile. By default, server logs are written to server profile folder. Logs/dumps/etc will be created there, along with BattlEye/BEC/Rcon related files. Windows Environment variables are supported (E.g. %userprofile%).
-doLogs - Enables all log messages in the server RPT file
-adminLog - Enables the admin log
-netLog - Enables the network traffic logging
-freezeCheck - Stops the server when frozen for more than 5 min and create a dump file
-filePatching - Ensures that only PBOs are loaded and NO unpacked data.
-BEpath= - Sets a custom path to the Battleye files
-cpuCount= - Sets the number of logical CPU cores to use for parallel tasks processing. It should be less or equal than the numbers of available cores.
-limitFPS= - Limits server FPS to specified value (current max is 200) to lower CPU usage of low population servers.
-mod=<string> - Loads the specified sub-folders for different mods. Separated by semi-colons. Absolute path and multiple stacked folders are possible.
-serverMod=<string> - Loads the specified sub-folders for different server-side (not broadcasted to clients) mods. Separated by semi-colons. Absolute path and multiple stacked folders are possible.
-storage=- Defines custom root folder for storage location.
'
Maybe they're breaking to include because of GSA handling

**Comment by mvaessen** [comment]
should be available now on the config template. Please let me know if it works

**Comment by LimitlessDrag0n** [comment]
Sorry for the late reply! As far as I can tell with those I wanted, it works! Thanks!!
