### ISSUE TITLE
Voting Task Triggering Erroneously for Player(s)

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#574]
**Describe the bug**
Upon logging into a game server connected to the voting rewards task, the task itself fires off. This repeats when a player transfers servers or logs back in the same day, without actually voting for the server itself. The voting task itself executes to fulfil its purpose (dispensing tokens to player, delivering an in-game message, delivering a discord message). There is a secondary task that will run when a player joins a server to check if they have voted and issue the voting rewards respectively, but when it activates, it appears that the task to dispense rewards fires numerous times. This secondary task has since been deactivated.  

Task ID - Voting Rewards: 3775(?)
Task ID - Check Votes for Characters Logging In: 3922(?)

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/44717221/01346e03-8dfa-4e94-ab3c-76b9521bcb4d)
![image](https://github.com/gameserverapp/Platform/assets/44717221/e2524c7a-2f0e-41e4-9bd8-e5b33cb85c5e)
![image](https://github.com/gameserverapp/Platform/assets/44717221/41513de0-8133-4977-9bb1-655a3c8da034)
(For the task history, they all seem to be triggering on Genesis 2 and Aberration)

**Comment by mvaessen** [comment]
thanks for reporting! This should be fixed
