### ISSUE TITLE
Discount code not allowing 100%

### ISSUE THREAD

**Issue by maplebacn** [gameserverapp/Platform#578]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I'm using supporter tiers to deliver in game items, so it goes direct through paypal instead of the token system,   when I apply a 100% discount code to my purchase, in this case a $5 chibi, it shows as $0 in GSA, but then it takes me to paypal and still tries to charge me $5   for 90% it shows the right discounted price on PayPal,

**Comment by mvaessen** [comment]
Thanks for reporting!
The option to give 100% discount is disabled, since this is not supported by payment service providers. The discount limit is set to 99%
