### ISSUE TITLE
GSA Integration Mod - Hidden Web Shop Tags

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#581]
For ASA, every shop pack with their own tags is displaying on the side column for filtering, even though clicking on said tags currently reveals nothing. This may be confusing to users that are unused to the system and may make them suspect bugs or errors. It would be preferable if the mod could parse and hide these tags if they belong to packs for other games, or if they're set to being hidden based on role. 

![image](https://github.com/gameserverapp/Platform/assets/44717221/85b5ff5a-e142-41af-b25e-3c98de49b98d)

**Comment by mvaessen** [comment]
this issue should be fixed now. Let me know if this issue still happens
