### ISSUE TITLE
Shop Pack : Settings : Description not visible on load

### ISSUE THREAD

**Issue by laurenskok** [gameserverapp/Platform#584]
**Describe the bug**
When editing a shop pack with a previously filled in description it will not show on first page load. You need to click into the WYSIWYG editor to trigger the rendering of the filled in description.

**To Reproduce**
1. Go to 'Shop Packs'
2. Click on 'One of the packs created'
3. Clkick on 'Settings'
4. You will now see an empty Description field; even if you had filled it in. 
5. However when you click on the field the content gets rendered

**Expected behavior**
Inserted description is visible from the start

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/12686222/efd9231f-d610-4c45-8588-3dab43e39b30)
![image](https://github.com/gameserverapp/Platform/assets/12686222/813e7234-3f01-49b6-a4e6-915544c9517b)

**Comment by mvaessen** [comment]
Going to address in #793
