### ISSUE TITLE
After clicking characters in the dashboard, this appears:

### ISSUE THREAD

**Issue by ssiwm** [gameserverapp/Platform#585]
![Screenshot_20231125_142932_Chrome.jpg](https://github.com/gameserverapp/Platform/assets/105603502/a12ccbf2-8bed-4e7b-863f-18019e2451e4)

**To Reproduce**
1. Go to dashboard 
2. Click on characters

**Comment by mvaessen** [comment]
Hi, this should be fixed now. Thanks for reporting

**Comment by ssiwm** [comment]
It works, thank you
