### ISSUE TITLE
Votes does not register on GSA

### ISSUE THREAD

**Issue by brothasx** [gameserverapp/Platform#588]
When voting on ark-servers with a steam account does not count to the players amount of votes, 
when using the !claim  command on discord it checks for votes to claim but stopts there. 

Hereby the pictures you asked for! 

![Screenshot_1](https://github.com/gameserverapp/Platform/assets/49365370/b8866451-8424-4329-a367-0379256fb800)
![Screenshot_3](https://github.com/gameserverapp/Platform/assets/49365370/80986e4d-7e1a-437e-b011-d0627e7af929)
![Screenshot_5](https://github.com/gameserverapp/Platform/assets/49365370/279a4506-27ca-49e6-84d8-9a2890d21573)
![Screenshot_2](https://github.com/gameserverapp/Platform/assets/49365370/e6bbbd1e-c3f6-4df1-938f-0a3cc574fbdd)

**Comment by mvaessen** [comment]
received update on discord that it's now working
