### ISSUE TITLE
ASA Shop : Shop pack without image is getting a random after page change

### ISSUE THREAD

**Issue by laurenskok** [gameserverapp/Platform#591]
**Describe the bug**
When opening the shop in game (Ark Ascended), and you switch from page then images will just appear random for the shop packs that have no image uploaded via GSA. 

**To Reproduce**
1. [GSA] Have enough shop packs so the shop needs to render a second page. 
2. [GSA] Have some shop packs with images and some without, make sure to spread them over the 2 pages. 
3. [INGAME] Open the shop 
4. [INGAME] Switch to the second page, and back to the first and so on. 

You will now see that the packs without an image will have an image from another pack. 

**Expected behavior**
If the pack has no image uploaded via GSA, then it should render the default image.

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/12686222/b4e12adf-2854-4402-8313-48910315198b)
Above image show second page, with the pack: "Blood : Volcanic" and has an image of cementing paste. However in GSA there is no image set for this shop pack. 

Note: If all packs have an image; there is no problem. The bug only occurs when it needs to render the default image due to the pack not having a custom iamge uploaded.

**Comment by mvaessen** [comment]
This should be fixed now, please let me know if it's fixed for you too
