### ISSUE TITLE
Variable not working with API commands

### ISSUE THREAD

**Issue by maplebacn** [gameserverapp/Platform#600]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
i'm trying to run this variable for the permissions  and ark shop plugin,  the variable seems to not be working, I checked on the api discord, and they sent me back over here,   the {ServiceID} Variable should be using EoS right?  did a bit of troubleshooting with spencer in the Ark-sa chat in discord,  we both discover that the Variables are not working with API commands.   I have mentioned this in the api discord,  they sent me back here noting that the gsa manager variables not doing what they should with the api

![image](https://github.com/gameserverapp/Platform/assets/81880747/dfc9ce85-ac65-4da0-b158-325417f4b696)

**Comment by mvaessen** [comment]
Can you please provide more info, like screenshots of generated commands? Or any other proof that gsa is not working as intended.

Gsa does not process commands differently for mods, plugins or anything.

**Comment by maplebacn** [comment]
Hey there, thanks for the reply,
There should have been a couple of screenshot in the bug report,   as well here is the start of the conversation between spencer and I in  your discord, https://discord.com/channels/315049169071112193/1166795937453199410/1179275363013115904

I have attached the screen shots of the commands being used again here

we have tried both serviceID and CharacterID    this shows a delivered notifier in the games top right corner, however nothing happens, there is no discord role given although the bot is att he top of my role list with the highest possible permissions, and no command sent to the api.   We tried this with basic ark commands like giving a weapon for example and it was fine,  it seems the command is not communicating with the API from what we can tell,  I did also try the command in game and it works fine, so the issue is also not that the api is not working correctly since I can manually input the commands.   It would seem to me that the variables are not being recognized by the ***@***.***
***@***.***
[photograph]
Joel Moroschan

P 250.618.3397
E ***@***.***
[twitter icon]<https://twitter.com/JoelMoroschan> [linkedin icon] <https://www.linkedin.com/in/joelmoroschan/>

**Comment by mvaessen** [comment]
closed due to not providing requested data. Please dont open issues unless there is actual proof this is a GSA bug.

**Comment by maplebacn** [comment]
I'm sorry what?  I literally just gave you the data that proved this was a gsa bug

[photograph]
Joel Moroschan

P 250.618.3397
E ***@***.***
[twitter icon]<https://twitter.com/JoelMoroschan> [linkedin icon] <https://www.linkedin.com/in/joelmoroschan/>
