### ISSUE TITLE
Shop pack section dashboard

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#612]
When there are many shop packs for various clusters on a single dashboard, it's very hard and time consuming for admins to manage them.

**Comment by mvaessen** [comment]
see #525

**Comment by babsgosgens** [comment]
Related: #674 

Not specifically related to clusters, but suggestion for change will apply. @mvaessen would you like me to close #674 and continue here?

**Comment by mvaessen** [comment]
@babsgosgens this dev item is mostly to fix some issues with the dashboard part of things. Folks have been (rightfully) complaining about how cumbersome it is so manage shop packs. So that needs some improvement. Any suggestions with regards to QoL on the dashboard-side of things with regards to shop pack can be added 👍
