### ISSUE TITLE
Bracketed Text causes ServerAdminPassword to break

### ISSUE THREAD

**Issue by scarecr0w12** [gameserverapp/Platform#621]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
When creating a server using Brackets, for example, with [text][like]this, The GSA system during startup will inject the servername and other start parameters into the Rcon password section of the ini. 

**To Reproduce**

- Create new ASA server
- Give server a name such as (Used during testing issue) `[5x][PvP]Test[TheCGN]Test`
- Open the GameUserSettings.ini and confirm current ServerAdminPassword section, In this example it is `ServerAdminPassword=JJB8H0jAUj` (Not an actual password and only used during testing)
- Start server
- If you wait for a period, such as while watching the log for the server to start, reopen the GameUserSettings.ini and you will see the following:
`ServerAdminPassword=JJB8H0jAUj?SessionName=[5x][PvP]Test[TheCGN]Test?MaxPlayers=70?MultiHome=0.0.0.0?NitradoQueryPort=27016?Port=7779?RCONPort=37016?RCONEnabled=true?ServerAdminPassword=JJB8H0jAUj?SessionName=[5x][PvP]Test[TheCGN]Test`
- Shut down the server and rename it to `[5x][PvP] Test [TheCGN] Test`
- Start server
- No issues with the ServerAdminPassword in the ini

**Expected behavior**
It should simply allow the name, and not adjust the ServerAdminPassword

**Screenshots**

**Additional context**
I am unsure of what exactly what formatting is causing it, only that the format that i have used has been shown to recreate the issue. During the entire process when the name DOES NOT have spaces, and causes the Ini to be changed, the GSA system does NOT see the server online. I expect this is because the rcon password is beign changed, and making the panel unable to login to verify the server is online. 

If needed for testing, my test server remains available.

**Comment by mvaessen** [comment]
Interesting issue. Took me a while to find what exactly was causing the problem. GSA will now automatically override the name to include a space in situations where the name contains: `a]a` (`a` is just an example character).
