### ISSUE TITLE
Shop: Does not show "" right

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#631]
I created a shop collection and I used " in the description. 

![image](https://github.com/gameserverapp/Platform/assets/99832504/a96dc1f2-beb6-4ea1-842e-9b8775a367b7)

Original text is: "Low Tier" (3) and "High Tier" (15)

**Comment by mvaessen** [comment]
![Screenshot_2023-12-14_16_42_07](https://github.com/gameserverapp/Platform/assets/13402423/3fc01fc7-48ca-4fb1-a52b-b98f11ff0756)

thanks for reporting! Should be fixed now.
