### ISSUE TITLE
Scheduled task runs a day early

### ISSUE THREAD

**Issue by scarecr0w12** [gameserverapp/Platform#632]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
A task set for 11 PM Friday ran on 11PM Thursday

**To Reproduce**
Create scheduled task, set for example, Friday 11pm
Let task run like normal

**Expected behavior**
Scheduled task should run on day and time set.

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/10427387/96e27011-149b-4d0d-a1b1-99cc78d83092) (Taken at 11:30AM Friday 12/08/2023)

**Additional context**
Time set for both the servers and GSA panel is America/Denver

**Comment by mvaessen** [comment]
Hi, could you please provide screenshots of the task history showing it running at the wrong moment?

**Comment by scarecr0w12** [comment]
![image](https://github.com/gameserverapp/Platform/assets/10427387/90bcedf0-3eec-43cb-8169-c240b63231ac)

**Comment by scarecr0w12** [comment]
![image](https://github.com/gameserverapp/Platform/assets/10427387/eb11f472-c30b-47b6-87df-9a59b8f6f6a8)

The one i have to swap my config back for sunday shows it'll trigger saturday aswell

**Comment by mvaessen** [comment]
Hm, perhaps is the timezone also impacting what the first day of the week is.
For me it seems to trigger at the right moment (just ran a test). 

Hopefully will be able to fix early next week. Thanks for reporting!

**Comment by mvaessen** [comment]
Update about the issue:
I was able to reproduce the issue when changing the timezone to `America/Denver`, which confirmed it is indeed caused by the timezone. 

Currently still investigating the issue to better understand what the potential solutions are and their impact.
