### ISSUE TITLE
Remove Custom Role via Player profile 

### ISSUE THREAD

**Issue by laurenskok** [gameserverapp/Platform#633]
**Describe the bug**
When removing a custom role via the player profile it gives you the green notification that the role was removed. But the role is still active and doesn't get removed. 
**To Reproduce**
1. Go to a profile from a player
2. Click on Custom Roles
3. Click on the red 'X'

(!) User is marked as multi account
(!) Test cases: 
- User had a previous role assigned after linking his account. (Multi account) ; then he got added to a new custom role. 
--> Unable to delete the old role
- When I manually add a second role; 
--> Able to delete the new role 
- When I manually add a second role; 
--> Unable to delete the old role

You will see that you get a green notification, but the role doesn't get removed.

**Expected behavior**
The role should been removed as intended via the CTA.

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/12686222/7a0332be-62aa-4d1b-8dbb-76bda978ce3c)

![image](https://github.com/gameserverapp/Platform/assets/12686222/10734a2d-e7ee-40fb-ab12-c2516733b2da)
![image](https://github.com/gameserverapp/Platform/assets/12686222/c528dd2e-c0d8-422e-aa15-fb55c82a5e95)

**Comment by mvaessen** [comment]
Hi, this should be fixed now. Thanks for reporting!
