### ISSUE TITLE
ASA Mod not appearing in Mod List

### ISSUE THREAD

**Issue by GnarlyVR** [gameserverapp/Platform#634]
**Describe the bug**
The map mod "Svartalfheim" for ASA has recently split into 2 versions. A Crossplay version that is only major updates, and a PC version with more updates that can be quickly hotfixed.

I am using the PC version, but am unable to see the crossplay version that was recently released.

This is the version that shows up:
https://www.curseforge.com/ark-survival-ascended/mods/svartalfheim

This is the version that is not showing up:
https://www.curseforge.com/ark-survival-ascended/mods/svartalfheim-crossplay

**Comment by mvaessen** [comment]
hi, sorry for the delay.
I'm not sure why this map specifically isn't showing up. I checked all other maps, and they all seem to show up.

It's a bit of a mystery why it's not showing up. I will continue my search and let you know when i found something.

**Comment by mvaessen** [comment]
![Screenshot 2023-12-13 at 12 43 38](https://github.com/gameserverapp/Platform/assets/13402423/3c67053b-10a6-4194-9c3c-57ae301a1b80)
should be fixed now. Thanks for reporting!
