### ISSUE TITLE
GUI's dont update

### ISSUE THREAD

**Issue by zerafox** [gameserverapp/Platform#644]
**Describe the bug**
Attempting to open most GUI's from the mod ingame either "time out" or just sit forever loading.
I've been on this for the last half hour waiting to see if it would update

**To Reproduce**
1. Login to Game
2. Use Radial wheel to open desired GUI option
3. Wait
4. Continue to wait....

**Expected behavior**
I expect after not too terribly long the GUI to update and display something

**Screenshots**
https://gyazo.com/4eaf01e35c5e91f1536107d1a4065317
Redirect: https://gyazo.com/f9c2698f6d2221b1815cb4ed868d1f0d (I don't even know what this is supposed to do)
https://gyazo.com/93bd71ab394e215a578001f7964f892a

**Additional context**
Rating appears to show up and work just fine.

**Comment by mvaessen** [comment]
Hi, can you check for errors in your configs? If you are using DediConnect, make sure you do not add any configurations for the mod in your INI's

**Comment by zerafox** [comment]
Seems we were still running some config settings, removed them and restarting the server. Will update with results.
Silly me

**Comment by zerafox** [comment]
Yeah that was it, apologies. Works smooth now xD
