### ISSUE TITLE
Group info not updating 

### ISSUE THREAD

**Issue by ASCWilderness** [gameserverapp/Platform#645]
Created a tribe, added another player.  Decided to create a new character, which deleted the old.  Admin'd myself back into tribe and took ownership.  New chatacter and old character have the same in game name.
Group info is not being updated on gsa even using manual update.

Server id: 30604/nehisksdz
![17025054561824936444618447742345](https://github.com/gameserverapp/Platform/assets/153316760/aa0de789-cadd-4a58-84de-dda0c816deb9)

**Comment by mvaessen** [comment]
Hi, i tried to access the FTP for the game server to test what data GSA was able to access, but FTP is blocking my connection attempt. So instead I ran a manual index, but nothing seems to change. 

Any chance you can check whether FTP is being blocked for GSA too? And if not, any chance you can temporarily lift your FTP firewall block so i can check it out?
