### ISSUE TITLE
Player/Character not in sync

### ISSUE THREAD

**Issue by JetJeager** [gameserverapp/Platform#649]
![image](https://github.com/gameserverapp/Platform/assets/152654934/a8f64e31-7ba9-4cbc-b91a-f6f829191f75)
https://dash.gameserverapp.com/admintools/accounts/faef9659-1415-49ab-a169-bffa91f17e9d
![image](https://github.com/gameserverapp/Platform/assets/152654934/e7788981-ec8c-415c-bee9-6ed2555b7585)

The player can connect and play but his character never syncs with his online profile.

**Comment by mvaessen** [comment]
Based on earlier discord feedback from Jet was apparently fixed with another bug fix

**Comment by JetJeager** [comment]
Yep this is all good on my end now.
