### ISSUE TITLE
ASA: Console Players

### ISSUE THREAD

**Issue by GnarlyVR** [gameserverapp/Platform#650]
With the new integration app update, my console players are reporting they are unable to use LB and right stick in for crouch.

**Comment by mvaessen** [comment]
hi, are you 100% sure this is caused by the GSA mod? Did you rule out any chance that this is caused by another mod / a recent ARK update?

**Comment by DieselEffect** [comment]
I have had over a hundred unique console players in the past 3 days and not one of them has reported this issue. They are most, if not all Xbox. I cannot speak for Playstation.

**Comment by Spencer021** [comment]
This was due to a plugin, woolys shop/shopUI plugin. It should be fixed

**Comment by mvaessen** [comment]
Going to close and assume it's some external issue
