### ISSUE TITLE
Connecting Patreon to GSA results in loop of sign-ins.

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#651]
**Describe the bug**
This was sent to me by a player in my community. Attempting to connect Patreon led to a loop of actions that resulted in an automatic bug report.

**To Reproduce**
See video

**Expected behavior**
Expected to link accounts

**Screenshots**
https://github.com/gameserverapp/Platform/assets/34605635/d63de167-ab2f-4315-baa5-2cebf87d58dc

**Additional Context**
Love the error GIF

**Comment by mvaessen** [comment]
- [ ] tribe connect discord
- [ ] mobile login

**Comment by mvaessen** [comment]
@DieselEffect the issue should be fixed now. At least, I can no longer reproduce the issue on my phone.

In cases where the phone switches to another browser during the login process, it might lose track of some important stuff. So in order for all that to work is it important that people perform the login / connect on their default browser. I hope that makes sense :)

**Comment by DieselEffect** [comment]
Thanks! I have notified the affected user and I'll close the ticket once I get verification from them that it works.

**Comment by DieselEffect** [comment]
From the affected user:

"So I tried logging into it with my browser but I can’t so I tried to reset my password and apparently I don’t have an account and my email isn’t working to reset it and I can’t even accept the confirmation email cause I can’t login the only way I can login is through the discord link you have in the Asa announcements"
![IMG_3561](https://github.com/gameserverapp/Platform/assets/34605635/83b8f750-91fc-4411-9a53-45359e0b71d8)
Video: https://github.com/gameserverapp/Platform/assets/34605635/c0905bdf-2fcb-4791-9ba0-a322c9537134
Video: https://github.com/gameserverapp/Platform/assets/34605635/d1966fd1-f664-469a-a53c-e7c91fe7de6e
"It’s like it didn’t take my email from my discord sign up and even when I save my email to the gsa account I receive an email but I click the link and I can’t login"
Video: https://github.com/gameserverapp/Platform/assets/34605635/733c56cc-57d8-43a5-9f6f-23146b2ab260
Video: https://github.com/gameserverapp/Platform/assets/34605635/a1727bb4-f833-4e7e-a99a-a8a0b795b2af
"Hopefully this is enough if you need more let me know. Just showing you that I do have an account"

**Comment by mvaessen** [comment]
Hi, i went ahead and deleted the image where it showed the persons email address.

Is this still related to the sign-in loop ?

- there is no reset password on the Community website. It simply does not exist
- GSA does not take any email address from social logins. People need to manually add this indeed. 
- just tested the "confirm email" flow and i cant reproduce any issues.

**Comment by DieselEffect** [comment]
As for if it's related, that is up to you at this point but this is the same person having the issue that triggered the original report.

**Comment by mvaessen** [comment]
The original report is about not being able to connect a patreon account due to a login loop. On my tests is this working fine, but if people use a non-default browser (not safari), which that person is. They need to make sure they configure their phone to use that browser as the default.

Let me know if that player is able to connect their patreon account to their account. If they can enter an email address, they are logged in.

**Comment by DieselEffect** [comment]
After a ...very... long discussion and troubleshooting process, we have determined that the Patreon link is now working as expected. Somehow this guy got so far off the instructed path that ...yeah anyways! Works great! Thanks Max!
