### ISSUE TITLE
Conflicting Information on Failed Delivery/Retry Timer

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#663]
**Describe the issue**
I'm not sure what caused this failure completely, but I can speculate that the container was locked due to an automated task to create a backup on the hour. I believe at this moment, the user purchased a shop pack item, resulting in failure and a 10-minute retry timer. Conflicting information was provided via multiple mediums.

__On Discord__
- GSA bot reported the delivery as Failed with no other context about the re-try timer. 

__In the Deliveries Section__
- Listed as "Scheduled" with mouseover information showing roughly 10 minutes after initial try

__In-Game__
- Tokens withdrawn from account, but no indication of failure other than lack of item in inventory (unverified by me, its possible the user did not see the notification, if one was sent)

In Conclusion:
- Obviously this type of thing has a very low probability of occurrence, but I feel like there's room for improvement here with the length of retry timer or the order of operations when it comes to the container being locked for backup or something of that nature. 10 minutes is a long time for someone who doesn't see the back-end operation of the server. With the nature of some communities on ARK, this is more than enough time for an end user to come to the conclusion that they have been scammed, even though that couldn't be farther from the truth.
- More communication from the Discord bot on the matter would be useful to admins who may field a ticket in that period on the matter.
- A message sent to the user that they can view on the community website, if possible, would also be useful.

**Section**
Discord Bot, Deliveries

**Screenshots**
- Initial Delivery Message: 
![image](https://github.com/gameserverapp/Platform/assets/34605635/59347273-73de-49cd-8f7e-981c7af6b4aa)

- Final Delivery Message:
![image](https://github.com/gameserverapp/Platform/assets/34605635/81b4e9c4-a8d8-4eab-98e4-d26e17ac4ba8)

- Discord Delivery Messages:
![image](https://github.com/gameserverapp/Platform/assets/34605635/dae5554f-ea13-449b-93ff-f46e6551a056)

**Additional context**
- Delivery ID: 24565142
- Small side issue: The error message in the screenshots says to check Game Server Events page, when I think that page/tab is now titled "Activity"?

**Comment by mvaessen** [comment]
Thanks for the detailed report. That helped me figure out what was going on much faster!

In future cases the `failed` error will be replaced with the error below. This only happens in cases where the delivery is going to retry.

![Screenshot 2024-02-20 at 14 20 21](https://github.com/gameserverapp/Platform/assets/13402423/b9aa4641-9a34-4d30-a635-34c6c793b00a)

**Comment by mvaessen** [comment]
This is now live
