### ISSUE TITLE
"Completed Deliveries" not working properly on Dashboard when filtering

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#666]
**Describe the bug**
When I select a filter (cluster, gameserver, etc), the "Completed Deliveries" goes to 0 for any time period.

**To Reproduce**
- Go to a Dashboard
- Add Widget
- Select Query Value (or anything)
- Data: Completed deliveries
- Filter: Anything other than *
- Time range: Any

**Expected behavior**
Value other than 0 when deliveries completed is >0

**Screenshots**
Filtered:
![image](https://github.com/gameserverapp/Platform/assets/34605635/364b4282-217b-400d-9372-4cd2788e1345)

With no filter
![image](https://github.com/gameserverapp/Platform/assets/34605635/87005cef-b7cd-43da-bd9e-9fac731c2051)

**Additional context**
The vast majority of the deliveries shown on the second screenshot have taken place on the "ASA Crossplay" cluster that is specified in the first screenshot.

Update: Issue seems to be with "Completed Deliveries" in any form, whether Query Value, Table, Graph, etc.

**Comment by mvaessen** [comment]
Thanks for the report!

for the most part this is a visual bug. The filter is not applicable in most cases because the delivery is send to a character and not a game server (kinda technical story). 

Currently opted for the easy fix, which involves hiding the filter.
