### ISSUE TITLE
Token Gem Blueprint Class Name not returning Token Gems

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#668]
**Describe the bug**
Token Gem Blueprint Class name not working in ConfigOverrideSupplyCrateItems configuration code.

**Example**
```ConfigOverrideSupplyCrateItems=(SupplyCrateClassString="SupplyCrate_Level03_C",MinItemSets=2,MaxItemSets=2,NumItemSetsPower=1.0,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="White Drop",MinNumItems=10,MaxNumItems=50,NumItemsPower=1,SetWeight=500,bItemsRandomWithoutReplacement=True,ItemEntries=((EntryWeight=250,ItemClassStrings=("PrimalItemConsumable_Seed_Test_C"),ItemsWeights=(50),MinQuantity=1,MaxQuantity=5,MinQuality=0,MaxQuality=0.236842105,bApplyQuantityToSingleItem=True,bForceBlueprint=False,ChanceToBeBlueprintOverride=0),(EntryWeight=250,ItemClassStrings=("PrimalItemConsumable_Token_GSA_1_C"),ItemsWeights=(50),MinQuantity=1,MaxQuantity=50,MinQuality=0.236842105,MaxQuality=2.368421053,bApplyQuantityToSingleItem=True,bForceBlueprint=False,ChanceToBeBlueprintOverride=0)))))```

This code string (written in Beacon) should give BerryBush Seeds and GSA 1-Token Gems every single time, but in-game, only gives BerryBush Seeds.

This was tested in a test server environment using all listed Class Names, capitalization configurations, etc. None have worked.

**Additional context**
Something about the Class Name is not functioning as it should. I looked up the class names for the old mod on Beacon (https://usebeacon.app/Games/Ark/Mods/2107956699/Engrams) and they are identical to the ones provided in GSA Docs (https://docs.gameserverapp.com/dashboard/integration_mod/#token-gems) - I noticed the folders were structured differently (slightly) in the new mod spawn commands than they were in the ASE mod, so maybe something was missed during the development process?

**Comment by mvaessen** [comment]
hi, based on reports from folks on Discord is this caused by using the wrong Beacon version. From what i can tell do you need the `alpha` version. I recommend asking the beacon folks for details

**Comment by DieselEffect** [comment]
I'm going to have to disagree with you on this one. I personally do not need beacon to write these INI parameters. The reason I opened this bug report is because I have looked over this code myself, broken it down and compared it to one item that does show up in the drops, and the GSA item that does not. I tried various configurations

![image](https://github.com/gameserverapp/Platform/assets/34605635/0f631082-83b0-4aa7-9323-b047b96a9d86)

Aside from all that, I think what that person meant by Beacon "Alpha" was Beacon "Omni" and that's what I'm using anyways.

**Comment by mvaessen** [comment]
Hi, a mod devs is going to take a look and see whether it's caused by something on our end. Expecting to get a word back this weekend

**Comment by mvaessen** [comment]
Based on info posted on Discord was this a mixup and was it working for other folks.

See
```
ItemEntries=((EntryWeight=250,ItemClassStrings=("PrimalItemConsumable_Token_GSA_10_C"),ItemsWeights=(50),MinQuantity=1,MaxQuantity=4,MinQuality=0.1125,MaxQuality=1.125,bApplyQuantityToSingleItem=True,bForceBlueprint=False,ChanceToBeBlueprintOverride=0)))))
```
