### ISSUE TITLE
Discord Bot: Name not displaying properly

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#681]
**Describe the bug**
My gameserver uses "&" in their name and the discord status card displays it "&amp;"

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/99832504/3b2afb55-45bb-4a78-8c16-83fb356d2a6d)

**Comment by mvaessen** [comment]
this should be fixed now. Please give it another try and close the issue when resolved 👍
