### ISSUE TITLE
Discord !vote throws error

### ISSUE THREAD

**Issue by keiran1993** [gameserverapp/Platform#690]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Discord !vote throws an error

**To Reproduce**
1. Add discord bot and set up voting with API key
2. !vote throws error on discord with a link
3. opening the link goes to a web page with an error. Cannot troubleshoot.

**Expected behavior**
Sends link of where to vote for server

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/116519866/cd176d77-1e13-48cc-8161-541abc10ddcd)
![Screenshot 2024-01-02 101431](https://github.com/gameserverapp/Platform/assets/116519866/590a9cbe-66fb-4ffb-b6ee-9128da122e76)

**Additional context**

**Comment by mvaessen** [comment]
Thanks for reporting. This should be fixed now
