### ISSUE TITLE
ServerAPI Versioning Causing GSA to load Older version

### ISSUE THREAD

**Issue by scarecr0w12** [gameserverapp/Platform#691]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Due to the versioning standard with the Ark ServerAPI system, it does not see, for example, version 1.1 correctly, and will instead load version 1.02 as it sees this as 1.2

**To Reproduce**
(From an already running server using 1.02)
1. Stop server
2. Remove ServerAPI 
3. Install actual latest version 1.1
4. Update will be available, restart
5. Server will auto-update (if enabled) to 1.02, or if you update server, it'll update to 1.02

**Expected behavior**
It should update to the latest version of 1.1

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by mvaessen** [comment]
Thanks for reporting. I've added a fix to deal with their versioning
