### ISSUE TITLE
The mod no longer exists

### ISSUE THREAD

**Issue by peteed** [gameserverapp/Platform#694]
The game says the mod no longer exists and opening the page in game says "This mod is no longer available due to violating content moderation rules." and suggests I remove the mod from my PC to free up the wasted space. The website on Curseforge is a 404 error. Can't find any info/news about this anywhere.

**Comment by mvaessen** [comment]
Hi, we posted about this earlier today. Please join discord for updates 

![Uploading Screenshot 2024-01-04 at 16.43.22.png…]()

**Comment by peteed** [comment]
Ahh yeah discord being the place to look kinda sucks for people like me when everyone expects me to join their discord to see news but discord limits how many servers I can join...

**Comment by mvaessen** [comment]
feel free to post a suggestion in this section to improve how information is shared with people that dont want to use discord 👍 
https://github.com/gameserverapp/Platform/discussions/categories/suggestions
