### ISSUE TITLE
Preventing the sending of tokens between players.

### ISSUE THREAD

**Issue by gutierrezx7** [gameserverapp/Platform#698]
**Describe the bug**
It is not possible to prevent players from sending tokens to other players via the Community website. There is an option to deactivate using the checkbox, however when you save the settings it returns checked.

**To Reproduce**
1. Go to 'dash.gameserverapp.com'
2. Click on 'Community, > Settings'
3. Scroll down to '
![image](https://github.com/gameserverapp/Platform/assets/85467051/046c987d-838e-4ded-b7dd-4aec18cf9ce3)
'
4. Uncheck the box and save.

**Expected behavior**
I think the feature of preventing the sending of tokens between players is important for the economy.

**Screenshots**
![msedge_sKSjVIjvdq](https://github.com/gameserverapp/Platform/assets/85467051/82170fef-2be1-4af8-af3d-0255deb57eca)

**Additional context**
 I remain at your disposal for further clarification or testing.

**Comment by mvaessen** [comment]
This should be fixed now. Let me know if it still doesnt work
