### ISSUE TITLE
Enable API Post Method

### ISSUE THREAD

**Issue by gutierrezx7** [gameserverapp/Platform#699]
**Describe the improvement**
Post and get requests to the API to collect player information such as: through Discord finding the Player's EOSID, collecting information about the number of tokens, sending tokens, reducing tokens, basic functionalities for future integrations with developments on Discord. 

> _This information is just for an example of functionality, it does not necessarily need to be this way or just this._

**Section**
API and Integrations

**Additional context**
I'm available to assist with testing and features, I'm an active developer and would love to work with tokens and my players' information on my Discord.

**Comment by mvaessen** [comment]
Hi, thanks for your suggestion. We are planning to expand the `System API`. This API is currently limitedly available.
