### ISSUE TITLE
Filter Label New Shop Packs

### ISSUE THREAD

**Issue by gutierrezx7** [gameserverapp/Platform#702]
**Describe the bug**
The new dashboard is not applying filters with Labels.

**To Reproduce**
**Screenshots**
![msedge_K1lTqlNsrk](https://github.com/gameserverapp/Platform/assets/85467051/0f1d3668-3365-4a30-8c4f-890eb1abb00d)

**Comment by gutierrezx7** [comment]
Tested and working!

**Comment by mvaessen** [comment]
Hi, thanks for the report. This should be fixed now.

Please reach out on discord so i can give you the `bug hunter` role
