### ISSUE TITLE
Can´t add multiple ASA mods to more Servers at the same time!

### ISSUE THREAD

**Issue by WEchoW** [gameserverapp/Platform#703]
### ARK: Survival Ascended GSA issue

**Can´t add multiple ASA mods to more Servers at the same time through the Install mod Broadcast thing, see the picture below:**
I think that Install Mod is working only for Steam mod IDs

![GSA Bug](https://github.com/gameserverapp/Platform/assets/155786268/97b94eac-ee8e-4974-b95b-1aa99da2bd25)

**Comment by mvaessen** [comment]
Thanks for the report! I add a alert explaining that this is only available for steam atm.
