### ISSUE TITLE
Calendar function (Website) dont see the registrations

### ISSUE THREAD

**Issue by PlayButtonYT** [gameserverapp/Platform#708]
Hello, I wanted to use the calendar function (Website) for player event registrations. 
The problem is that I can't see who has signed up for the event. 
I can see the number, but not the individual person. Is there a way to view the registrations?

![11](https://github.com/gameserverapp/Platform/assets/152392349/73e7eec1-11b2-4635-8702-163e96ae43bc)

<img width="677" alt="12" src="https://github.com/gameserverapp/Platform/assets/152392349/b28864f8-a121-40f3-ab1f-0d6d25abd4fe">

**Comment by mvaessen** [comment]
Thanks for the report. You should be able to see the participants now
