### ISSUE TITLE
Tribe logs and Website 

### ISSUE THREAD

**Issue by JetJeager** [gameserverapp/Platform#714]
![image](https://github.com/gameserverapp/Platform/assets/152654934/e55ddf65-05b7-417b-8747-ec75667d84c3)
![image](https://github.com/gameserverapp/Platform/assets/152654934/bb1cbe31-a869-44ed-b9eb-3f9e8b9383ea)
![image](https://github.com/gameserverapp/Platform/assets/152654934/015dc38f-3db8-4785-b21b-f41dc4b7594c)
Cant connect to discord. When you try it says restricted.

**Comment by mvaessen** [comment]
hi @JetJeager as mentioned on discord: please send me a message when you are available for checking this out.

**Comment by JetJeager** [comment]
Will do max.

**Comment by mvaessen** [comment]
@JetJeager is this still happening?

**Comment by JetJeager** [comment]
Looks to be updating correctly now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
