### ISSUE TITLE
Restrict Access Issues

### ISSUE THREAD

**Issue by Spencer021** [gameserverapp/Platform#719]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
When trying to setup restrict access I am getting an error saying "Please change the Windows Display language to English to Continue" I have checked via system settings and with PowerShell and they both say its set to English. I do have the English windows version installed as well.

**To Reproduce**
Enable Restricted access

**Expected behavior**
It connects

**Screen Shots**
![image](https://github.com/gameserverapp/Platform/assets/58157745/fe5d48cd-0002-4cc7-a87d-b6ebbd2a48ff)
![image](https://github.com/gameserverapp/Platform/assets/58157745/6f33a873-d2bd-4ff7-b2e6-188ec8ed7194)
![image](https://github.com/gameserverapp/Platform/assets/58157745/22a886ec-08a8-4b53-983b-e8c59dab2b27)
![image](https://github.com/gameserverapp/Platform/assets/58157745/41ae2c10-3083-4b58-8903-f7a9abef4a43)

**Comment by mvaessen** [comment]
i made some changes, can you try again for me please @Spencer021
