### ISSUE TITLE
Satisfactory not loading properly (Windows Server may effect Linux too)

### ISSUE THREAD

**Issue by Kriz02** [gameserverapp/Platform#725]
The server seems to install fine, can update all the config files, once you start the server it will load to 0.01 GB to 0.1GB and does not show up in game. The executable file is showing under task manager, seems like the server is online, but there is now way to connect to it in game. 

Tried using a blank configuration so the game would be all defaults
Tried using Query and Game ports
Tried using direct connect
Tried exiting the game and reloading it

So Far nothing has worked

**Comment by mvaessen** [comment]
Satisfactory should work again on Windows and Linux now.

If you already had a running Satisfactory server, please follow these steps:
- At the machine danger zone section -> Docker images -> delete gameserverapp-satisfactory
- Reinstall the satisfactory game server

⚠️ If your game server does not work initially (or after restoring a backup), try start it a couple times (especially on Windows). This seems to fix the issue.

let me know if you experience any issues 👍
