### ISSUE TITLE
topgameservers.net API key validation failed

### ISSUE THREAD

**Issue by Zangador** [gameserverapp/Platform#730]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Claimed my server on topgameservers.net.
After that i got the API key and tried to apply it on gameserverapp platform. 
Tried this alot of times but always getting the same error "API key validation failed
![Screenshot 2024-01-19 103856](https://github.com/gameserverapp/Platform/assets/12024013/31e1b8dc-6910-4b39-a9af-ec05d7d8a8a2)
![Screenshot 2024-01-19 104715](https://github.com/gameserverapp/Platform/assets/12024013/b693ec5d-63c2-4456-bf33-a26107f2886c)
"

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by Panda369420** [comment]
Ive also came across this, finally today i reached out to them in their discord and they tested my API and its all working, i checked to make sure i didn't have any space before or after the key, made sure it was all correct with upper and lowcase letters, and still same thing.

**Comment by mvaessen** [comment]
Hi, i tested this just yet and it seems to work without any issues.
Try refresh the page after adding the api key and saving the page.

![Settings_-_Vote_rewards_-_GameServerApp_com](https://github.com/gameserverapp/Platform/assets/13402423/3a93bd96-4c5d-414d-87b2-b524ec0acb6f)

**Comment by Zangador** [comment]
I had a great conversation with the TopGameServers.net support, and it appears NITRADO causing this trouble thanks to its firewall. After their investigation, the conclusion is they cant help me while i am on NITRADO.
