### ISSUE TITLE
Palworld broadcast posts only first word

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#736]
GSA generated restart message
![image](https://github.com/gameserverapp/Platform/assets/13402423/f810c471-5066-4850-a79a-07c2176f3900)

**Comment by scarecr0w12** [comment]
Palworld broadcast requires any space use a _ in replace of it, or no spacing at all. I would also note, it cuts off after about 40-60 characters, nomatter what.

**Comment by mvaessen** [comment]
this is getting more hilarious by the day. what the heck!

**Comment by mvaessen** [comment]
So after testing, the conclusion is that their broadcast command is broken and stop processing the rcon command after the first space.

Replacing it with `_` for now
