### ISSUE TITLE
[Palworld] Server info panel says Offline (loading...) even though server is up and running

### ISSUE THREAD

**Issue by D3vJohn** [gameserverapp/Platform#739]
This problem is happening randomly.

Game Server ID 35089

https://discord.com/channels/315049169071112193/945483534150303784/1199469223349604484

**Comment by ssiwm** [comment]
same here, servers are up and running

![obraz](https://github.com/gameserverapp/Platform/assets/105603502/4255b8d2-b09a-4148-b73b-12cb1bf64151)

**Comment by mvaessen** [comment]
Based on current observations and reports from other folks that were helping test: it's most likely caused by Palworld going beyond a certain load, causing certain RCON commands to struggle with providing data.

Hopefully this will improve in the future.
