### ISSUE TITLE
[Palworld] Use the query port to determine the online player count

### ISSUE THREAD

**Issue by D3vJohn** [gameserverapp/Platform#740]
Palworld is experiencing many issues with RCON, and it's not showing reliable information. Using the query port to get information for the game server would be better.

The reason I am suggesting it, because sometimes the server panel shows online with 0 members. Even though the server is up and running with many users on.

**Comment by mvaessen** [comment]
palworld has a rest api now https://tech.palworldgame.com/category/rest-api
