### ISSUE TITLE
[Palworld] banlist.txt gets overwritten with empty data upon restart

### ISSUE THREAD

**Issue by D3vJohn** [gameserverapp/Platform#742]
Game: Palworld

I've noticed that this problem keeps happening, and I've checked it multiple times, and all indications say that the file is written over upon a scheduled server restart. I looked at the modified date, and it's the same exact time as the restart.

OS: Linux

**Comment by mvaessen** [comment]
Hi, gsa will populate the banlist file based on the bans @ gsa. When banning folks via the gsa dashboard, that file should get populated

**Comment by D3vJohn** [comment]
> Hi, gsa will populate the banlist file based on the bans @ gsa. When banning folks via the gsa dashboard, that file should get populated

Hi Max, since RCON is unstable and I cannot see online users through GSA all the time, I manually ban people by adding them to the file. So how can I ban people within GSA if I cannot see their steamid? Is there a manual way for that to make sure that the ban stays?

**Comment by mvaessen** [comment]
Should be possible via https://docs.gameserverapp.com/getting_started/other/migrate_server/#4-import-ban-list

**Comment by D3vJohn** [comment]
> Should be possible via https://docs.gameserverapp.com/getting_started/other/migrate_server/#4-import-ban-list

I just tried it but it doesn't work. The banlist.txt stays empty even after importing. Here is something that might be helpful, below is the format for Palworld's bans:

**steam_{steamid}**

Also, Palworld doesn't save them line by line, it saves them on the same line like:
steam_{steamid}steam_{steamid}

**Comment by mvaessen** [comment]
you might need to hit the `start` button, as the system is currently configured to only populate the banlist on startup. When you hit the `start` button it should populate the file.

I can disable the action for now, but i'd think it would be easier to manage via the dashboard, in cases where you dont have access to the files

**Comment by mvaessen** [comment]
The banlist should now update with the right format. Let me know if you experience any issues
