### ISSUE TITLE
[Palworld] Duplicate "SaveGames" folders

### ISSUE THREAD

**Issue by D3vJohn** [gameserverapp/Platform#743]
First Location: /SaveGames
Second Location: /serverfiles/Pal/Saved/SaveGames

Both were created at the same time, and both are regularly updating.

OS: Linux

This issue could be related to: https://github.com/gameserverapp/Platform/issues/742

**Comment by D3vJohn** [comment]
Here is another observation, when I manually edited the banlist.txt to add back the people I banned before, it automatically updated the file in both locations even though I only modified the second location.

**Comment by mvaessen** [comment]
hi, which OS is this and what are the full paths?

**Comment by mvaessen** [comment]
i see this on a fresh install:

<img width="497" alt="Screenshot 2024-01-28 at 16 01 29" src="https://github.com/gameserverapp/Platform/assets/13402423/fed8167c-ca5b-492b-8a38-ea1c66cc585d">

<img width="631" alt="Screenshot 2024-01-28 at 16 01 14" src="https://github.com/gameserverapp/Platform/assets/13402423/7a7525de-2452-4688-b10c-5990c181e7a6">

**Comment by D3vJohn** [comment]
> i see this on a fresh install:
> 
> <img alt="Screenshot 2024-01-28 at 16 01 29" width="497" src="https://private-user-images.githubusercontent.com/13402423/300272125-fed8167c-ca5b-492b-8a38-ea1c66cc585d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Njg5NjcsIm5iZiI6MTcwNjQ2ODY2NywicGF0aCI6Ii8xMzQwMjQyMy8zMDAyNzIxMjUtZmVkODE2N2MtY2E1Yi00OTJiLThhMzgtZWExYzY2Y2M1ODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE5MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYTQxNzE4MGE3NTlhMDhiMTg1YTdhNDRkYzg2MjBjNmQ2OTMwMDIyNzUxZjk4YTdhMzcyMzVhMDI1Y2YzMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kDV35SeaYctm4e0H0byGa8It-2fZkVu_QKgnE7gWyIk"> <img alt="Screenshot 2024-01-28 at 16 01 14" width="631" src="https://private-user-images.githubusercontent.com/13402423/300272122-7a7525de-2452-4688-b10c-5990c181e7a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Njg5NjcsIm5iZiI6MTcwNjQ2ODY2NywicGF0aCI6Ii8xMzQwMjQyMy8zMDAyNzIxMjItN2E3NTI1ZGUtMjQ1Mi00Njg4LWIxMGMtNTk5MGMxODFlN2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE5MDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzFjODBiNzUyZjIyYzVhNWRhMDhlYjhlNjdiMWE0ZDcxZmFiODJkNjk3NDVmM2ZiMjc3OGQ5ZTdhMzlkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xIg4FRWmrH3rYYRs3ZRQqbsHxBpDs9iCVSVBxkFE13o">

Ubuntu 22 to be more specific

I just installed the game server again, and below are the two absolute paths:

- /home/GameServerApp/containers/ewzuocysk/ftp/SaveGames
- /home/GameServerApp/containers/ewzuocysk/ftp/serverfiles/Pal/Saved/SaveGames

**Comment by mvaessen** [comment]
Yes, completely normal. See the "ftp" folder. It's to facilitate the ftp bind, without causing security risks like ftp breakout
