### ISSUE TITLE
Palworld. Player indexing.

### ISSUE THREAD

**Issue by ad3d0** [gameserverapp/Platform#747]
Duplicate character are being "registered" in GSA with `00000000` Character ID.

This happens because after client receives authorization to join by the server "placeholder" all zeroes ID is assigned until character is fully loaded, then actual charter ID is assigned to a client. So if GSA happen to run `showplayers` command while someone is in the middle of loading on the server, duplicate character like you can see on pictures below is being indexed.

As a solution I would suggest GSA to ignore all results with Character ID `00000000` and not include those in indexing and listing.

![image](https://github.com/gameserverapp/Platform/assets/43604113/31b4ac8a-d5ef-414a-914c-c05e6cd08611)
![image](https://github.com/gameserverapp/Platform/assets/43604113/6a86b658-c316-4ccd-904c-2ccbb9765fee)
![image](https://github.com/gameserverapp/Platform/assets/43604113/5689c815-dba3-456d-b8a6-e45d9298167b)

**Comment by mvaessen** [comment]
thanks for reporting, this should be fixed now!
