### ISSUE TITLE
Large font in chat despite GSA mod

### ISSUE THREAD

**Issue by Dalo1101** [gameserverapp/Platform#749]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
![2b1d9892-3a40-41c2-94a0-c1f32e04dbef](https://github.com/gameserverapp/Platform/assets/155737937/56cc0280-a2b7-483c-b58a-e01f04e4b2a8)
![2b1d9892-3a40-41c2-94a0-c1f32e04dbef](https://github.com/gameserverapp/Platform/assets/155737937/26e98ddc-4233-4bc7-8e6c-3a5cb1ea8ebd)

The GSA mod (no shop) is installed. Yesterday evening the chat was still normal. This morning the font size was the same as when the mod is not installed.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by mvaessen** [comment]
I just pushed an update that should fix this issue. Please allow a couple minutes to pass and let me know if the issue still happens
