### ISSUE TITLE
Admin Teams: Team Member getting E-Mails about server without access to

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#768]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
A admin team member get's emails of servers he don't have access to

**To Reproduce**
I don't know how to reproduce

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/99832504/c17ffe5a-888b-4ddb-b4e1-fa8d18b95b11)
![image](https://github.com/gameserverapp/Platform/assets/99832504/b81b9365-599f-4d6d-a7b6-3c6a15595353)

https://click.pstmrk.it/3s/dash.gameserverapp.com%2Fgameserver%2F32604%2Factivity/SQlE/tVqzAQ/AQ/b78f1150-2a1e-4478-8898-7d52a5822aae/2/J64AOouoHs
When he clicks on thsi link he gets to the namalsk but he has not access to it

**Comment by mvaessen** [comment]
Thanks for reporting! This should be fixed now
