### ISSUE TITLE
Restoring backups for ASA restore to wrong folder

### ISSUE THREAD

**Issue by mvaessen** [gameserverapp/Platform#784]
files are being restored to `svartalfheim_wp ` while it should restore to `svartalfheim`.

**Comment by mvaessen** [comment]
Still seems to happen in certain situations

**Comment by mvaessen** [comment]
This was announced on Discord:
Hi @Ark:SA folks on @DediConnect !

⚠️  This only applies to ARK: SA.

While looking into a problem with backups, I noticed that there still is an issue with backups for ASA ONLY, but it only seems to happen with certain maps. 

Long story short
Certain maps store their saves in folders that are different from the map name (see example below). This can causes problems with GSA in certain cases, as GSA tries to find the files based on the provided map name.

Examples:
Temptress -> Temptress/Temptress_WP.ark
Scorched Earth -> ScorchedEarth_WP/ScorchedEarth_WP.ark
The Island -> TheIsland_WP/TheIsland_WP.ark
ARK: Nirvana -> IsekaiArk/Isekai_WP.ark

Origin
GSA tries to create backups without wasting disk space. So it only grabs what is necessary and ignores what is not.
But, when GSA is unable to reliably figure out which folder stores the files that should be included in the backup, there is a chance backups dont store any data when the map & folder name are different (see ARK: Nirvana example above).

COMING UP: Increased backup sizes for ASA
Due to the circumstances is it safe to assume that GSA will never be able to reliably figure out what the right folder to back up is, for ASA. And because of that, is it probably best to backup everything inside the SavedArks folder, so we can ensure reliable backups.

However this will lead to much larger backup zips, since we'll be storing approx. 10x the data per backup.
I'm hoping to push this update later today, assuming testing goes well.

Are current ASA backups safe?
The honest answer is (for ASA at least): i dont know.
For official WC maps I'm fairly confident that those are 100%, but for other maps it mostly depends on how the map dev named their files & folders.

---

✅  The fix has been deployed. Please keep in mind that this wont fix the issue retroactively. It only fixes the issue going forward

**Comment by birdman3131** [comment]
![Screenshot_20240410-091435](https://github.com/gameserverapp/Platform/assets/749937/47823550-972e-4f42-bb13-9d4eae0304f5)
I'm inclined to believe this broke something.

**Comment by mvaessen** [comment]
Thanks, this should now be fixed
