### ISSUE TITLE
Tasks are not working correctly.

### ISSUE THREAD

**Issue by Kriz02** [gameserverapp/Platform#789]
Tasks that are supposed to check if a player has a custom role are not working properly. 

It should go through each task and check when a player logs in, it should first go through the list to see if they are part of a VIP group, if they are a part of a certain VIP group, it should then move to a sub task that checks if they have gotten their Daily reward, if not, it gives them the reward, then sets a 24 hour role which prevents them from getting that reward for 24 hours, then it checks for a weekly reward, gives them the reward and sets a custom role that lasts 1 week, it should then no longer give them that reward. 

The issue is it seems to ignore the "HAS" option completely and is giving the players rewards for all custom roles when they only have 1 out of the 8 different roles, then it is giving them rewards for all 8 roles every time they login, that is making the delivery system work overtime and just causing chaos across all ASE maps we have. 

I need to know if this system is working as it should, or if I need to create my own for ASE as I have for ASA.

**Comment by mvaessen** [comment]
Can you post a screenshot of your task for me please?

**Comment by mvaessen** [comment]
closing due to lack of info
