### ISSUE TITLE
2nd posting of Server Status

### ISSUE THREAD

**Issue by zerafox** [gameserverapp/Platform#790]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Bot occasionally and seemingly randomly posts a second "server status" message instead of continuing to update the existing message like it had been.

**To Reproduce**
1. Set up a server status posting
2. Wait an undetermined amount of time 🤷 
3. See second posting of same server status

**Expected behavior**
I expect the bot to just continue to update the existing post for a server like it does most of the time.

**Screenshots**
https://gyazo.com/b28af6c0fdfb75cbd92b6eef0e549b05

**Additional context**

**Comment by mvaessen** [comment]
The issue seems to happen after 6 weeks, which is very close to a timer that is used in this feature. So i'll review this and use a different method to ensure the message keeps updating the existing message
