### ISSUE TITLE
Merge Shop pack & Supporter Tier edit + setting pages

### ISSUE THREAD

**Issue by jimouwerkerk** [gameserverapp/Platform#793]
__Please make sure to leave out any sensitive information__!

**Describe the bug**

**To Reproduce**
1. Create a collection shop pack
2. Create 2 or more sub packages
3. Add something in the subpackages
4. Save the shop package (not sub packages)
5. Shop package is saved and last sub package is saved, but not the other sub package

**Expected behavior**
My expectation was that all sub packages would be saved.

**Screenshots**
Before save:
<img width="1548" alt="Screenshot 2024-03-07 at 09 13 29" src="https://github.com/gameserverapp/Platform/assets/17004836/30755c39-cc6e-4489-9b07-e2aa2b5350b5">

After save:
<img width="1540" alt="Screenshot 2024-03-07 at 09 13 36" src="https://github.com/gameserverapp/Platform/assets/17004836/94d65e4d-2729-4a46-99ac-8436e6cc5345">

**Additional context**

**Comment by mvaessen** [comment]
Hi, sub packages need to be saved individually at the moment. See the `Save settings` button below the actions, per sub pack

**Comment by jimouwerkerk** [comment]
@mvaessen Oke. Then there is maybe a warning missing like the subpackage save do have? It gives no "Are you sure" warning right now. Thats why I assumed it would be all saved instead of just the last one.

**Comment by mvaessen** [comment]
For me it is posting a `Are you sure?` message when i tried to save another sub pack.
However it doesn't seem to show that warning when using the save button in the top-right.

**Comment by jimouwerkerk** [comment]
@mvaessen Exactly, thats what I mean and why I thought it would save all sub packages with that button. If the "Are you sure" message is there, then I know not everything will be saved.

**Comment by mvaessen** [comment]
Upon further inspection is it probably best to refactor the page and combine the `sub packages` & `settings` pages into one, like we did for the Tasks pages

**Comment by mvaessen** [comment]
- [ ] Merge shop pack content & setting pages
- [ ] Merge supporter tier content & settings pages


Update docs
- [ ] shop single settings
- [ ] shop collection settings
- [ ] supporter tier settings

**Comment by NobleKangaroo** [comment]
> * [x]  Merge shop pack content & setting pages
> * [x]  Merge supporter tier content & settings pages
> 
> Update docs
> 
> * [x]  shop single settings
> * [x]  shop collection settings
> * [x]  supporter tier settings

Nice change, removing the need to click between tabs, but might I add a suggestion? Can we possibly move the "Presentation" card to the left side above the commands, to reduce right-side clutter and use some of that extra space on the left side? It looks a lot better that way imo.

#### Current state:
![image](https://github.com/user-attachments/assets/453e67fc-07af-45b1-ba3e-b5428707bff8)

#### Proposed change:
![image](https://github.com/user-attachments/assets/e2203917-cfd7-4c60-b264-8b440dd21c72)

**Comment by NobleKangaroo** [comment]
> thanks for the issue report. That should be fixed soon. For the other issues, it's probably best to post a suggestion.

Looks good, Max. I've spent some time making a very detailed suggestion (#953) with animated preview of what it would look like, to visually illustrate these changes.

Cheers, have a great one!
