### ISSUE TITLE
Discord Embeds and Variables not Cooperating

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#799]
I was attempting to make a "receipt"-type log that would post an embed with a character's Discord ID, Steam, and service ID. It looks like just the EOS/Service ID will display. I was wondering if it's possible at all to separately display any attached Steam 64ID, Discord ID, EOS ID, etc.?
![image](https://github.com/gameserverapp/Platform/assets/44717221/cb050b72-73ea-4a19-b068-c3b1d29a4275)
`json
{
  "content": null,
  "embeds": [
    {
      "title": "One (1) Growth Voucher - Ready to be Redeemed",
      "description": "**User:** {serviceid}\n**Discord:** {user}\n**Steam:** {steamid}",
      "color": 6881279,
      "fields": [
        {
          "name": "How to Use:",
          "value": "To tally up how many active vouchers, use one of the available IDs to look up the user and count.",
          "inline": true
        },
        {
          "name": "Completed",
          "value": "When the growth voucher is redeemed, delete this post. No further logging is needed.",
          "inline": true
        },
        {
          "name": "Trouble?",
          "value": "If unable to locate a voucher, message <@217119930951270401>.",
          "inline": true
        }
      ],
      "thumbnail": {
        "url": "https://upload.gameserverapp.com/pATPaIUP1kQa257orAD9NycARQWecfq8irugun99.png"
      }
    }
  ],
  "avatar_url": "https://upload.gameserverapp.com/pATPaIUP1kQa257orAD9NycARQWecfq8irugun99.png",
  "attachments": []
}
`

![image](https://github.com/gameserverapp/Platform/assets/44717221/c5787358-b256-409c-a6f4-8b4d3f4c5ccd)
Did a test using a discord text message action item, and it looks like it'll actually source the discord user/{user}.
![image](https://github.com/gameserverapp/Platform/assets/44717221/80146e4a-9a52-4de6-a0eb-fec2f6bc478c)

**Comment by mvaessen** [comment]
Thanks for reporting!

Upon further investigation did I find a bug that was preventing `{user}` from being replaced with the Discord name. This should be fixed in the next deployment
