### ISSUE TITLE
Connect account to EOS does not trigger when someone connect their account.

### ISSUE THREAD

**Issue by jimouwerkerk** [gameserverapp/Platform#800]
**Describe the bug**
Connect account to EOS does not trigger when someone connect their account. Task history doesnt show it being executed after several people connected their account.

**To Reproduce**
1. Make a task for connecting account to EOS
2. Connect player with EOS (!getconnectcode ingame)
3. Task is not executed

**Expected behavior**
Expected that the task will execute

**Screenshots**
<img width="1544" alt="Screenshot 2024-03-16 at 11 12 44" src="https://github.com/gameserverapp/Platform/assets/17004836/829ba1ad-6ae9-4bde-becf-ac37476b0b93">

**Additional context**
I've tried it with "Execute only when player is online" toggled on and off, no difference in here.

**Comment by mvaessen** [comment]
This should now be fixed. Was a bug indeed.

**Comment by jimouwerkerk** [comment]
Tested it. It works now. Thanks!
