### ISSUE TITLE
Your old game servers

### ISSUE THREAD

**Issue by StevieSenpai** [gameserverapp/Platform#814]
**Describe the bug**
when you try to reinstall a deleted server you get an error about payments and several ID's.

**To Reproduce**
1. Go to 'your servers and delete some server, when you do it you will get a section that says Your old game servers'
2. Click on 'install the deleted server, select the disk where you are going to install the server again'
3. Scroll down to 'the button that says Install game server now once you have selected the disk where the server will be reinstalled'

**Expected behavior**
server cannot be restored.

**Screenshots**
  
![screenshots](https://github.com/gameserverapp/Platform/assets/150964621/f211249d-48a5-43ac-b1d5-8ed69b589e6f)

**Comment by mvaessen** [comment]
Currently trying to reproduce, but it seems to work for me.
Anything specific you have selected? 

![Screenshot 2024-04-04 at 14 09 38](https://github.com/gameserverapp/Platform/assets/13402423/05def4ad-5e5e-40d8-a04e-3e8c9dc2efb2)
![Screenshot 2024-04-04 at 14 09 50](https://github.com/gameserverapp/Platform/assets/13402423/75371120-9362-4de6-b8bd-e24a673f5a2d)

**Comment by mvaessen** [comment]
ah, nvm, it seems to happen when no machine is selected !

**Comment by StevieSenpai** [comment]
The first time I thought it was because I didn't select the machine, but then I made sure that if I selected it and didn't do it only with the disk, the error came out anyway :(
My files were being installed on the D disk, I don't know if that has something to do with this problem

**Comment by mvaessen** [comment]
hi, have you tried again after this issue was changed to `to be tested`? it should be fixed now
