### ISSUE TITLE
[Palworld] Reinstall created a whole new SaveGame folder 

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#821]
**Describe the bug**
It was a warm evening in April...anyways,

A user reached out to me stating that the game was in a restart loop.

I reinstalled the container to eradicate the pesky loop.

Upon reinstall, the server created a whole new SaveGame folder.

After conferring with some guy named Max and finding [this message in Discord](https://discord.com/channels/315049169071112193/1199098550278168586/1200848172172460062), I downloaded the GameUserSettings.ini file via FTP, put the old SaveGame folder name into the DedicatedServerName= parameter, uploaded it back in, overwriting the existing file, and started the server back up.

This reverted the server back to its previous state. The reporting user confirmed "All is good". I popped a bottle.

Additionally, the GSA dashboard shows the backup files to be >200MB when it appears via FTP that they are only 10-11MB.

**Expected behavior**
I would expect a container reinstall to not create a whoooole new woooooorld for me to have to put my nerdy glasses on to fix.

**Additional context**
Start managing servers, they said. It will be fun, they said.

**Comment by mvaessen** [comment]
Thanks for reporting!
This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.
