### ISSUE TITLE
RCON {character.id} Varible not working for scriptcommand

### ISSUE THREAD

**Issue by ADDWIRE** [gameserverapp/Platform#834]
**DESCRIPTION**
I'm trying to spawn a tame with a mod on my server; the command works using my EOS ID when I manually put it in the command line, but when I put in {character.id} into the command line, it doesn't work. 

**Server Log when it doesn't work "GiveItemToPlayer': Bad or missing property 'PlayerID' when trying to call GiveItemToPlayer"**

**To Reproduce**
1. `scriptcommand PCS.SpawnDino {character.id} Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP' 150 100 0 `
2. It doesn't work
3. `scriptcommand PCS.SpawnDino 0002b1dXXXXXXXXbXXx79bcb5b7eXXXa Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP' 150 100 0`
4. The Command Works.

**Expected behavior**
A Cryopod spawns in the player's inventory with a dino inside.

**Screenshots**
No Screenshots

**Additional context**
The command works when I manually enter the Player EOS But Doesn't when the {character.id} Variable is inserted. Also {Character.id} works for items being delivered 100%

**Comment by mvaessen** [comment]
Hi, this section is only for gsa issues. For help with in-game commands you can check out our discord and use one of the game channels.

**Comment by ADDWIRE** [comment]
Thanks, I thought since GSA isn't translating the variables correctly for that command, that it should be here. Who do premium members get support? is there a ticket system?
