### ISSUE TITLE
Discounts not calculating properly (100% discount, "You do not have enough tokens")

### ISSUE THREAD

**Issue by NobleKangaroo** [gameserverapp/Platform#840]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Discounts are not currently checking if the player's balance is above the discounted price, but instead the pre-discount price. For instance if I have a balance of 100,000 tokens and a store item costs 200,000 pre-discount, a 100% discount should allow me to purchase the item. However, the store says that I do not have enough tokens.

**To Reproduce**
1. Create store item with price, for instance 200k
2. Create role giving 100% discount, assign to player
3. Go in-game with that player and try to purchase the item

**Expected behavior**
Allowed to purchase the item

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/34781835/5d2363c5-c4e7-46de-97bd-30bde359e201)

**Additional context**
N/A

**Comment by NobleKangaroo** [comment]
Hello @mvaessen - I can confirm that a 50% discount role works as intended. My test case was a shop item for 150,000 tokens and a discounted rate of 50% and a player with a balance around 100,000. This did in fact work, resulting in the player with a remaining balance around 25,000 as intended.

That said it appears that the issue is not with the before/after balance comparison (both ) but possibly with a zero-cost shop pack. I have a use case where a player might be offered a 100% discount, and this is something that should be working as a 100% discount role is something that the website allows us to do.

I'm able to perform more testing if you need, let me know.

Thanks!

**Comment by mvaessen** [comment]
Thanks for reporting!
This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.

**Comment by NobleKangaroo** [comment]
> Thanks for reporting! This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.

Good to go, thanks!!
