### ISSUE TITLE
Dashboard not totaling "Total Donated" on player pages

### ISSUE THREAD

**Issue by Decollates** [gameserverapp/Platform#843]
What it says on the title. The screenshot doesn't cover the entirety of what the player has purchased through the shop, but I was shy with screencapping the total amount, haha...

![image](https://github.com/gameserverapp/Platform/assets/44717221/6319687f-f878-4595-9442-dc4a88817140)

It's happening with other players, including those that are paying through Patreon. 
![image](https://github.com/gameserverapp/Platform/assets/44717221/c360c867-defc-44f2-bfb5-2dcf88f0d929)

**Comment by mvaessen** [comment]
Thanks for reporting!
This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.
