### ISSUE TITLE
Custom Roles - AutoMations - Whitelists

### ISSUE THREAD

**Issue by ADDWIRE** [gameserverapp/Platform#844]
### Custom Roles don't have benefits. 

- Can only set discounts for subscriptions and shop Packs. However, discounts do not apply at checkout, and users are sent to the merchant gateway with the full amount to be paid.
- Can't perform any task once a member becomes a custom role.
- would like to apply whitelisting for servers for certain roles like admins, or users.

**Expected behavior**

- discounts should work for Custom roles; loss of sales as a result
- should be able to program tools for when a user becomes a role, have tasks start, i.e., apply whitelisting for admins, etc.
- would like to have automation for emails for when a user is coming up on renewal for their subscriptions, or if a sale starts.

**Comment by mvaessen** [comment]
Hi, thanks for the report and suggestions. As mentioned on discord. Please make sure to create separate suggestions for each suggestion (make sure to search whether there are any existing suggestions, to avoid duplicates).

This section is for bug reports only.

**Comment by mvaessen** [comment]
closing this
