### ISSUE TITLE
"Only run when game server is online" still generating sub-tasks for offline servers; task being disabled after multiple failed runs

### ISSUE THREAD

**Issue by NobleKangaroo** [gameserverapp/Platform#855]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Sub-tasks attempting to be run on offline servers despite "Only run when game server is online" being enabled. Because of this happening, tasks are automatically being disabled.

**To Reproduce**
1. Create a task with one or more clusters selected for "Run for selected cluster(s):" in the settings and one or more actions
2. Observe the task attempting to be run on offline servers

**Expected behavior**
Servers that are offline should not have sub-tasks generated

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/34781835/8cac08f9-c4a6-4f81-979b-15f28fa4921c)
![image](https://github.com/gameserverapp/Platform/assets/34781835/fa944069-83e1-46d2-ba45-efc844b776ef)

**Additional context**
This also presents errors if you select specific servers instead of "run for selected cluster(s)".

**Comment by mvaessen** [comment]
Hi, could you provide logs indicating the game server was indeed offline at the time of running? I'm not aware of any issues atm

**Comment by NobleKangaroo** [comment]
Hi @mvaessen - there are no logs because the game servers are brand new and have never been powered on. Are there any specific logs from specific pages you would like me to gather? I'll provide what I can, but this should be fairly easy to reproduce by creating a cluster of two servers (one powered on and one powered off) and observing the behavior. Willing to do anything I can to help though. Thanks!

**Comment by mvaessen** [comment]
Hi, does it still happen when you start and then stop the servers?

**Comment by NobleKangaroo** [comment]
Yes, I powered on and back off one of these servers and the task is still failing on the server with "Only run when game server is online" enabled. The red-boxed server is the one I powered up and down and waited for the task to run and it still counted it as failed.
![image](https://github.com/gameserverapp/Platform/assets/34781835/04ee240c-3f2e-41f3-81f0-79c736daf2aa)

Here's another copy of the task settings for reference.
![image](https://github.com/gameserverapp/Platform/assets/34781835/195a18cb-f223-4f46-8a98-68270cba2cde)

**Comment by mvaessen** [comment]
okido, thanks for the update. I'll make sure to check it out.

On a side note: i see you have a `worldsave` task. Please do note that, while you can use tasks for this, it's not a reliable way. I recommend using ARK's native save methods to avoid problems when there are connection issues between GSA and your machine.

**Comment by NobleKangaroo** [comment]
Thanks for the insight. I had switched to using a scheduled task as players were noticing periodic "lag" during saves of ARK's The Island map. The ability to do this in a task also allows me to send a broadcast "World save in progress" to let players know the world is being saved which is actually helping to pinpoint the world save as the cause of the lag. I'll keep this in mind for the future, however, in case we ever have issues with the command not running. And if there are connection issues here and there, perhaps I could add ARK's native method back in, but as a 1 hour or 2 hours save instead of every 15 minutes, that way any lag caused by world saves would be limited to those (non-message broadcast) saves. Thanks again!

**Comment by mvaessen** [comment]
Thanks for reporting!
This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.

**Comment by NobleKangaroo** [comment]
> Thanks for reporting! This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.

Good to go, only runs on servers that are online. Thanks!!
