### ISSUE TITLE
Tasks with conditions counting condition sub-actions towards main actions; different than randomizers

### ISSUE THREAD

**Issue by NobleKangaroo** [gameserverapp/Platform#856]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
When creating tasks with conditions, each condition's actions count towards the overall count. This is not the case when creating tasks with randomizers; each of the the randomizer cases have their own action counts that do not affect the main task's action count. As a result, it's necessary to create many tasks that do the same thing instead of a single "switch" type task with multiple "case" style statements.

For instance to award 10 different roles a different amount of tokens every 30 minutes, you would need to create 10 different tasks that each have a condition to check the player is in a role and the action of sending tokens. This is inefficient as it creates many unnecessary task runs on the server side and pollutes the task run logs on our side.

This could be fixed by counting the conditional itself as an action towards the overall actions, and each condition could have the paid-for amount of sun-actions. This is the behavior seen with randomizers - each randomizer counts towards the overall actions, but each randomized option has its own count of actions, and they're both set to the paid-for limit (in add-ons).

**To Reproduce**
1. Create a task with two conditionals
2. Add actions to each conditional
3. Observe the actions from both conditions being counted towards the overall action count
4. Compare this to the randomizer, which does not exhibit this behavior

**Expected behavior**
Conditionals to have their own action counts, similar to randomizers, and not be counted towards the overall action count.

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/34781835/592ba2c8-c18f-443f-b8e7-2d8ea871b98a)
![image](https://github.com/gameserverapp/Platform/assets/34781835/4a4dbf6b-b1bb-4863-ad95-0cb967a69d2a)

**Additional context**
As mentioned, randomizers do not exhibit this behavior, and it's therefore necessary to create a ton of tasks instead of just one that can handle everything. This again serves to pollute the task run logs, and probably causes at least some load on the server, all of the smaller tasks running instead of them just running as one larger task.

**Comment by mvaessen** [comment]
Hi, this is by design.

**Comment by NobleKangaroo** [comment]
Appreciate the response. So you're still limited, for instance (by add-on plan) to 10 actions overall and not 10 per conditional. That's by design? Is there any chance you'd look at implementing a "switch" wherein you could pick something like "player has role" and have multiple cases and individually-limited sets of actions more like the randomizer? Thanks much!

**Comment by mvaessen** [comment]
yes, the tasks/deliveries will limit you to X number of actions per delivery. The reason why the randomizer does let you add more, is because ultimately there is only 1 action being performed (+ picking one random option).

Conditionals are by themselves performing actions and do count towards the limit, because they otherwise would be able to bypass the action limit per delivery. 
See these message on Discord, for more details: https://discord.com/channels/315049169071112193/693116872857747506/1196493834704654428
https://discord.com/channels/315049169071112193/693116872857747506/1205560623719645294

**Comment by mvaessen** [comment]
PS for suggestions, please make sure to post those in the suggestion section so they wont get lost 👍

**Comment by NobleKangaroo** [comment]
> yes, the tasks/deliveries will limit you to X number of actions per delivery. The reason why the randomizer does let you add more, is because ultimately there is only 1 action being performed (+ picking one random option).
> 
> Conditionals are by themselves performing actions and do count towards the limit, because they otherwise would be able to bypass the action limit per delivery. See these message on Discord, for more details: https://discord.com/channels/315049169071112193/693116872857747506/1196493834704654428 https://discord.com/channels/315049169071112193/693116872857747506/1205560623719645294
Ah I understand. It didn't dawn on me that you could use this to have an infinite amount of actions with a cleverly concocted task. ;)

> PS for suggestions, please make sure to post those in the suggestion section so they wont get lost 👍
Sure! Want to run this past you here but I'll post it there as well if you think it's something you'd be able (and willing) to do. What about something like this? I did a mock-up in dev tools but a UI that combines a picker-like UI that lets you specify one or more custom roles and token amounts as well as a message. It would have the benefit of allowing tokens to be sent to multiple custom roles, not being able to be abused, and also cleaning up the number of tasks that have to be created by the user and run on the server.
![image](https://github.com/gameserverapp/Platform/assets/34781835/86cd3597-9acb-4fc4-925f-760a198a88d6)

**Comment by mvaessen** [comment]
Feel free to post it on suggestions. If more people like to see something like that added, they can upvote. Requests with a good amount of votes are candidates for being added. 👍 

can't provide any ETA's on when stuff is being added.
