### ISSUE TITLE
Valheim Server FTP test failed

### ISSUE THREAD

**Issue by Eurymachus** [gameserverapp/Platform#862]
Valheim server showing 'FTP test failed' error.

**To Reproduce**
1. Go to 'Valheim' cluster
2. See 'Eurys Community Server' Valheim server
3. Observe the 'FTP Test Failed' error

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/1562316/ff59fa09-01fa-446a-a8b4-2ce982a134de)
![image](https://github.com/gameserverapp/Platform/assets/1562316/456d3956-0356-4df6-81ec-e6005e7ef836)

**Additional context**
Our Valheim server was successfully installed just after Ashlands released (after a few failures) and has been running perfectly ever since, without issue.

When in the Dashboard this evening I noticed that the Valheim server was showing the 'FTP test failed' error.

I was however able to connect to the game server and the FTP, but I noticed that the 'serverfiles/Saved/worlds_local' folder was missing,

When I checked the logs I could see that at 22:33 on 2nd June the log showed that the server 'disconnected' then 'connected' and from that moment on attempted saves failed with the 'Error saving world! Could not find file'.

When in game (as admin) clicking on the 'Save' button produced the same error in the log.

To allow the game to save I created the 'worlds_local' folder, uploaded a backup of the 'Ironman.fwl' file I had and then clicked the 'Save' button in game. A successful Save was created and I downloaded a backup of the files created, though I do not know if this save will launch correctly or if indeed it is a 'proper' save.

I am still unable to interact with the server via the GSA dashboard and when clicking on the 'Retry installation' nothing happens.

**Comment by mvaessen** [comment]
Hi, this is a local issue. I posted more info on your discord report
