### ISSUE TITLE
Enshrouded Update

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#864]
Not a bug but wanted to let you know about the new update of Enshrouded.  New Json will be configured:

{

    "name": "Enshrouded Server",

    "password": "",

    "saveDirectory": "./savegame",

    "logDirectory": "./logs",

    "ip": "0.0.0.0",

    "queryPort": 15637,

    "slotCount": 16,

    "userGroups": [

    {

    "name": "Admin",

    "password": "Randomized password 01",

    "canKickBan": true,

    "canAccessInventories": true,

    "canEditBase": true,

    "canExtendBase": true,

    "reservedSlots": 1

    },

    {

    "name": "Friend",

    "password": "Randomized password 02",

    "canKickBan": false,

    "canAccessInventories": true,

    "canEditBase": true,

    "canExtendBase": true,

    "reservedSlots": 3

    },

    {

    "name": "Guest",

    "password": "Randomized password 03",

    "canKickBan": false,

    "canAccessInventories": false,

    "canEditBase": false,

    "canExtendBase": false,

    "reservedSlots": 0

    }

    ]

}

https://enshrouded.zendesk.com/hc/en-us/articles/19191581489309-Server-Roles-Configuration

Dont know if its the right place for informing

**Comment by mvaessen** [comment]
Thanks for the update! It looks like the only thing changed is the new `usergroups` stuff, right?

**Comment by LimitlessDrag0n** [comment]
Yes, almost. The usual password for the server is switched out with this setting so it's no server password needed anymore
