### ISSUE TITLE
V Rising Backups not working

### ISSUE THREAD

**Issue by seyshell** [gameserverapp/Platform#866]
**Describe the bug**
Since the patch the saved game folder has moved, and backups are not working

**To Reproduce**
1. Go to 'Backups'
2. Click on 'Backup'
3. Once completed Backups are 0 bytes

**Expected behavior**
A backup with saved games withing.

**Screenshots**
If applicable, add screenshots to help explain your problem. __Please make sure to leave out any sensitive information__!

**Additional context**

**Comment by mvaessen** [comment]
Thanks for reporting!
This should be fixed now. Please give it a try and if it is indeed fixed, you can close this issue.
