### ISSUE TITLE
Community Website - Mobile Version Issues

### ISSUE THREAD

**Issue by TDodgeCo** [gameserverapp/Platform#884]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I'm getting multiple reports from users, and have confirmed on my own mobile device as well as an emulated one via dev tools, that the mobile hamburger menu at best is unresponsive on my community site, and at worst results in an infinite loop of Cloudflare verifying the user.

Aside from shop packs, I've made 1 edit to my community site - adding the supporter tiers standard link to the header nav.

**To Reproduce**
1. On mobile, or via dev tools mobile emulator, navigate to https://shovl.premiumark.net
2. If able to get past initial cloudflare verification, attempt to interact with the mobile hamburger menu.
3. See error

**Screenshots**
User reports: 
https://i.imgur.com/mR72lwT.png
https://i.imgur.com/rpVwqCR.png

Other:
https://imgur.com/xFH0h4K
https://i.imgur.com/OISBZrI.png
https://i.imgur.com/6ViEPZS.png

**Comment by mvaessen** [comment]
Im not sure what you are trying to explain about the hamburger menu. I can't see any issues there.

As for the captcha problems, I can reproduce those and they seem to hit 100% reproduce rate on mobile phones.
I've submitted a report with cloudflare. This seems to be a common issue, but for some reason there is no solution provided on their docs:

- https://community.cloudflare.com/t/after-js-challenge-success-cf-send-request-as-post-even-though-it-s-a-get-url/281847
- https://community.cloudflare.com/t/js-challenge-changes-get-request-to-post/300387
- https://community.cloudflare.com/t/after-js-challenge-success-than-cf-send-request-as-post-even-though-it-s-a-get-url/373164

**Comment by mvaessen** [comment]
![Screenshot_2024-07-25_at_11_29_23](https://github.com/user-attachments/assets/9cd64c29-3491-4695-9b66-4b9f5447d080)
Cloudflare is looking into the issue

**Comment by mvaessen** [comment]
Hi, sorry for the delay.

This should be resolved now. It was caused by a HTTPS redirect apparently. Please reopen if you still experience this issue.
