### ISSUE TITLE
Changing config template on running server produces a "Whoops!" error

### ISSUE THREAD

**Issue by NobleKangaroo** [gameserverapp/Platform#890]
**Describe the bug**
Changing config template on running server produces a "Whoops!" error

**To Reproduce**
1. Go to running server
2. Change config template
3. See error

**Expected behavior**
Config template to change without error, even though application requires a server restart

**Screenshots**
![Screenshot_20240726_173507_Chrome.jpg](https://github.com/user-attachments/assets/6d3b0867-e6c9-4867-85a4-ebed8b7359b2)

**Additional context**
N/A

**Comment by mvaessen** [comment]
Thanks for the report! I got a fix coming up, but may take a bit to complete testing.
For now the easy work around is turning off `sync blueprint` switch

![Screenshot_2024-07-27_at_00_26_11](https://github.com/user-attachments/assets/d50f9124-8e9d-4850-9122-ed58ad0cbedd)

**Comment by NobleKangaroo** [comment]
> Thanks for the report! I got a fix coming up, but may take a bit to complete testing.
> For now the easy work around is turning off `sync blueprint` switch
> 
> ![Screenshot_2024-07-27_at_00_26_11](https://github.com/user-attachments/assets/d50f9124-8e9d-4850-9122-ed58ad0cbedd)
> 

Awesome work as always. Thanks!!
