### ISSUE TITLE
Discord bot links not using custom domain

### ISSUE THREAD

**Issue by Pho3niX90** [gameserverapp/Platform#897]
**Describe the bug**
After setting up a custom domain, it seems the bot is still using the subdomains when posting to discord. I noticed this specifically for the player activity. 

**To Reproduce**
Reproduction is simple, setup a custom domain, have the bot post player activity to a channel, you will notice it still uses the generic subdomain.

**Expected behavior**
To use the domain setup. 

**Screenshots**
![image](https://github.com/user-attachments/assets/5e8a8282-f846-45e2-a2d6-4561b09bcc13)
![image](https://github.com/user-attachments/assets/c79d6585-d923-4ef1-9447-5473ede5ae5b)

**Comment by Pho3niX90** [comment]
It seems after login in, it also redirects to the subdomain instead of the custom.

**Comment by mvaessen** [comment]
Hi, are you 100% sure your domain is all ✅ and there are no domain errors?
