### ISSUE TITLE
ASE server not restoring backups.

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#909]
ASE servers appear to not be restoring backups.

Server: 53142 is one that can be tested

As seen here the backup contains all the files.

However upon restoring the backup nothing shows in the folder.

![image](https://github.com/user-attachments/assets/dc8db91a-dcea-43e0-9a83-e726c628e879)

![image](https://github.com/user-attachments/assets/e98134d2-c68d-48b0-8b54-04237a6a7150)

The backup was taken just prior to a wipe for testing.

Server was a fresh server installed 3 or 4 days ago.

**Comment by mvaessen** [comment]
problem was found and fixed. Will need to test all games on all platforms to make sure this isn't introducing new issues for other games

**Comment by mvaessen** [comment]
Tested all games, on both OS's, except:

- Atlas (Windows)
- Last Oasis (both)

**Comment by mvaessen** [comment]
@birdman3131 this should be fixed now. Can you give it a try?

**Comment by birdman3131** [comment]
So. ... It seem fixed although i came a hairsbreadth from claiming it was not. 

Going to open a separate issue but at least one of my servers is not backing up anything but the map file itself. And guess which server i was testing the backups on? 

Fix one bug find 5 others.

**Comment by mvaessen** [comment]
I tested all game servers except the ones mentioned above, and confirmed for each the backups are working.

Did you confirm the backups had files in it?

**Comment by birdman3131** [comment]
The backup is missing the files which was why I was gonna open a separate issue as I am fairly sure this issue is fixed.
