### ISSUE TITLE
Character Problem

### ISSUE THREAD

**Issue by hereiamcme** [gameserverapp/Platform#911]
I have this set up on an ark server. I have a player who can not link to the shop website and the only thing I can think of is for some reason her character name is not the same as her in game character name. I'm not sure why it did this and I'm not sure how to fix it. When she types !getconnectcode in chat nothing pops up yet it does for everyone else. I tried to have her make a new character but that one just showed as a ? on the player panel and didnt even show her online.

**Comment by hereiamcme** [comment]
i know how to link the character the problem is it wont let her and im pretty sure its because when u look in players on the game server webpage its named her character differently then in the actual game so it wont give her the code in game.

**Comment by hereiamcme** [comment]
also not understanding why when some people make new characters they show up as a ? with no character on the webpage

**Comment by mvaessen** [comment]
Hi,

As mentioned, this section is not for support. If you need help, please join discord.
