### ISSUE TITLE
Api docs link is broken

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#916]
https://dash.gameserverapp.com/configure/api The API docs link leads to a page not found.

**Comment by birdman3131** [comment]
Not sure if its not been deployed or not but it is still doing it. (Gave it an hour and a few hard refreshes.) To be more specific there is an underscore rather than a dash in the url. https://docs.gameserverapp.com/developers/community_api vs https://docs.gameserverapp.com/developers/community-api

**Comment by mvaessen** [comment]
which link are you referring too?

**Comment by birdman3131** [comment]
![image](https://github.com/user-attachments/assets/1dea2eb6-c1c0-45f0-86c4-64a1ad1b70b5)

**Comment by mvaessen** [comment]
ah, I completely missed that one. Thanks! Will be fixed in the next update
