### ISSUE TITLE
Game variables do not get interpolated on Discord

### ISSUE THREAD

**Issue by babsgosgens** [gameserverapp/Platform#917]
**Describe the bug**
Some variables do not get interpolated in the Discord message.

**Screenshots**
![image](https://github.com/user-attachments/assets/bcedebc8-6768-44e0-91f3-d00d0f990453)

**Additional context**
Related Discord thread: https://discord.com/channels/315049169071112193/1285936980890353776

**Comment by Kami-prog** [comment]
maybe this will help
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by mvaessen** [comment]
I tried to find this task on your dashboard, and copied the content of your message there.
When trying the same thing, it seems to work without any problem.

![Image](https://github.com/user-attachments/assets/de61d1ff-0b0f-4448-851f-186a4165ebd6)

**Comment by mvaessen** [comment]
going to assume that this was due to a missing website name. Feel free to reopen if the issue still happens. When you do, please include screenshots ruling out the suspected cause
