### ISSUE TITLE
Backup "0" confirmation message on rollback actions

### ISSUE THREAD

**Issue by babsgosgens** [gameserverapp/Platform#936]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
When installing a rollback, the confirmation message does not seem to recognise the backup identifier/name. This is makes me think that the backup is corrupted.

**To Reproduce**
1. Go to Server --> 'Backups'
2. Click on 'Game server pulldown'
3. Click on 'Actions'-->'Restore'

**Expected behavior**
I would like to see a confirmation that indicates that the requested backup will be installed.

**Screenshots**
![image](https://github.com/user-attachments/assets/59ab8039-c85c-400a-99c4-4f5ea42ec872)

**Comment by mvaessen** [comment]
Thanks! looks like it's just an issue with the name not properly displaying on the popup

**Comment by mvaessen** [comment]
did you try to restore the backup with the date, or the pre-shutdown?

**Comment by mvaessen** [comment]
This should be fixed now. Please let me know if it is or not
