### ISSUE TITLE
Unable to archive a Config Template that says its attached to servers. The servers in question were 'Destroyed'

### ISSUE THREAD

**Issue by Eurymachus** [gameserverapp/Platform#938]
**Describe the bug**
I tried to archive a Config Template but received an error saying 'The template you are trying to archive has servers connected. Please disconnect all servers before archiving the template.'

The servers in question have been 'Destroyed' (I had logged a previous issue about not being able to destroy them and this was fixed)
https://github.com/gameserverapp/Platform/issues/847

**To Reproduce**
1. Click on the template list
2. Click to Archive the template
3. Receive the error message

**Expected behavior**
Template should be archived since there are no servers that reference it.

**Screenshots**
![image](https://github.com/user-attachments/assets/f2457a87-fe03-49a6-ae42-1234c4923f70)

**Comment by mvaessen** [comment]
Thanks for the report, can you include the link to your config template here for me please? So i can look it up

**Comment by Eurymachus** [comment]
Sure thing!

https://dash.gameserverapp.com/config-template/7610

**Comment by mvaessen** [comment]
This seems to have been caused by old GSA:Hosted game servers still being present on the dashboard. It should be removable now
