### ISSUE TITLE
DayZ: Launchparams don't get deleted

### ISSUE THREAD

**Issue by LimitlessDrag0n** [gameserverapp/Platform#941]
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I removed 

"-doLogs -adminLog"
from my launchparams in my config template but they persist. After I deleted them and saving, I added "test", to see, if those gets overwridden. It's added to the file but the old settings persist. 

**To Reproduce**
1. Go to Config Template
2. Click on a template for daYz and add launch params
3. start the server so that the file gets created, stop it again, change values, start again

**Screenshots**
![image](https://github.com/user-attachments/assets/8b437ea3-b18b-4d3b-8804-b8315d34b3b3)

**Additional context**
I did not change anything in the file! I just opened it to see if it changed. 

**ADDITION: after removing "test" again, test dissapeard but do logs and adminlog is still there

**Comment by LimitlessDrag0n** [comment]
Sorry, the error is, that those lines are not deleted "-dologs -adminlogs". There is no error to see as in a file or such. 
I don't see, where I can add those arguments somewhere else. I checked the server if I set it somewhere but the only files I find it in are in the gsa.ps1 and in the folder "server_manager" server_manager.ps1.

I added "-dologs" a while ago and thought, removing those out of my config templates launch params will delete them also from the start script

I noticed this because one mod, needs this disabled and the server wont start, when dologs is still active

**Comment by mvaessen** [comment]
hi, what you're referring too are settings that are configured by GSA. They can't be removed and are used to show the logs on the GSA dashboard..

**Comment by LimitlessDrag0n** [comment]
Okay, I understand. A bit sad :D but now I know. Maybe I can find a work around for this...

**Comment by LimitlessDrag0n** [comment]
Possible to add a function to enable or disable if needed?

**Comment by mvaessen** [comment]
what option do you need removed and why exactly. It sounds a bit weird that a mod only works when you disable the logs

**Comment by LimitlessDrag0n** [comment]
Some bought mods need it disabled, as I learned today, because this checks for dependencies, as far as I understand. For my case I need -dologs disabled so that the mod don't need those dependencies enabled so that I can use the mod without installing a different one so that they work

**Comment by LimitlessDrag0n** [comment]
I hope I understand this correctly. Yes. Other Mods have no issues to be installed. I only bought one mod this time, and this is the first time I ran into this. 

Maybe for some day on your to-do. Thanks for your time.

**Comment by mvaessen** [comment]
What I meant to say, is that if I understand you correctly, the issue can be solved by installing an additional mod. Right?

> so that the mod don't need those dependencies enabled so that I can use the mod without installing a different one

Based on what you said, it sounds like the easy fix is to install the required extra mod.

Feel free to submit a suggestion, on the suggestion section, if you like to see the logs being optional. Probably easier to just install the dependent mod though 😄.
