### ISSUE TITLE
Error message getting character name from different character

### ISSUE THREAD

**Issue by babsgosgens** [gameserverapp/Platform#949]
**Describe the bug**
I just noticed that the delivery shows the name of my character on Club Ark, while I am instead selecting a character (Sara) with a different name on a different map (Astraeos).

The item does get delivered to the correct character though.

**To Reproduce**
1. Go to 'Shop Packs'
2. Select the player

**Expected behavior**
I would have expected to read the following:

> Ready to send "Mastercraft Fishing Rod Blueorint" to character "Sara".

**Screenshots**
![image](https://github.com/user-attachments/assets/c80ae2a5-e17f-4f0c-8882-68d1ddcc7655)

![image](https://github.com/user-attachments/assets/c7b21e71-52b6-4554-b8a9-738b9089da68)

**Comment by mvaessen** [comment]
Thanks for reporting, this should be fixed now
