### ISSUE TITLE
Trigger / event tasks with "Player voted [X] times [since]" condition don't appear to be triggering

### ISSUE THREAD

**Issue by NobleKangaroo** [gameserverapp/Platform#951]
## **Describe the bug**
Trigger / event tasks with "Player voted [X] times [since]" condition don't appear to be triggering

## **To Reproduce**
1. Configure voting on ark-servers.net
2. Create a "Player voted" trigger / event task
3. Create a "Player voted [X] times [since]" trigger / event task
4. Vote for your server on ark-servers.net
5. Observe "Player voted" trigger / event task working but not "Player voted [X] times [since]" trigger / event task

## **Expected behavior**
Both trigger / event tasks should work

### Working trigger / event task for "Player voted"
![image](https://github.com/user-attachments/assets/b2fff310-80bf-498b-98ca-9190ea94c607)

### Similar not-working trigger / event task for "Player voted [X] times [since]"
![image](https://github.com/user-attachments/assets/2dd4fb1b-6f7d-4ee1-add3-8888d590c423)

## Additional context
Attempted several things to see if any of them had any impact:
  - Changing the number of required daily votes from 3 to 1
  - Disabling "Run actions when player is online" (to allow the task to run when the player is offline)
  - Enabling the task on all clusters and all servers (though you can normally just select the cluster(s) needed)
  These changes do not appear to have helped

**Comment by mvaessen** [comment]
Thanks for the report. This should now be fixed. Please give it a try and let me know

**Comment by NobleKangaroo** [comment]
> Thanks for the report. This should now be fixed. Please give it a try and let me know

Awesome. I've tested it and had a couple players do the same and it appears good now. Thanks for the great work!
