### ISSUE TITLE
Only run when server is online seems to work differently than worded

### ISSUE THREAD

**Issue by birdman3131** [gameserverapp/Platform#969]
So I have a task set to run every few minutes.

If I have Only run when server is online selected the task still runs when the server is offline but creates a subtask that fails. After enough fails the task gets disabled.

Expectation would be that the task does not run on any offline servers rather than trying to and failing.

(I have since set it to allow running while the server is offline and everything is working so this is not a pressing issue. Just one I would mention)

![image](https://github.com/user-attachments/assets/e87030d7-6843-4c0f-9ad2-7dce9a4ce48f)

**Comment by mvaessen** [comment]
can you add a screen of the task actions?

**Comment by birdman3131** [comment]
https://dash.gameserverapp.com/task/edit/61455

As a note the Only run when game server is online has been disabled for now on the task.




![image](https://github.com/user-attachments/assets/b050ef11-1d01-4a80-8d1e-723ad2039795)
![image](https://github.com/user-attachments/assets/4c2b68bf-63a4-4d6e-b427-19d2b1bb46b0)

**Comment by mvaessen** [comment]
based on the screenshot it looks like `Only run when game server is online` is turned off.

**Comment by birdman3131** [comment]
> based on the screenshot it looks like `Only run when game server is online` is turned off.

It is now but when it was turned on the task was failing if the server was turned off.

It may be a wording issue but "only run when server is online" does not read as "run but fail when server is offline." to me.

**Comment by mvaessen** [comment]
please make sure you turn it on, then try again and let me know if it happens again with that setting turned on.

**Comment by birdman3131** [comment]
Again. Not a critical bug as turning that off works. Just thought I would report it.

**Comment by mvaessen** [comment]
![Screenshot 2024-11-20 at 18 22 38](https://github.com/user-attachments/assets/07305dd4-8f1b-420e-a834-83c029c8d7a9)
it must look like this. On your screenshot it is turned OFF

**Comment by birdman3131** [comment]
https://dash.gameserverapp.com/task/history/65239781 It is currently enabled with the server off and failing.

**Comment by mvaessen** [comment]
okido, thanks for the info. Will take a look

**Comment by birdman3131** [comment]
![image](https://github.com/user-attachments/assets/0cc7564c-f729-4885-9e23-3840a46ad942)
 So now the main task fails instead of the subtask.

https://dash.gameserverapp.com/task/history/65616550 / https://dash.gameserverapp.com/task/edit/61446

**Comment by mvaessen** [comment]
In this case it is intended behavior. If there are no game servers online for a task, it should disable itself at some point to avoid useless tasks from running

**Comment by birdman3131** [comment]
I will preface this by saying we have switched to a different task based on a char logs in trigger so this is not something that currently has any effect on my setup.

I would still argue that "Only run when server is online" does not translate into run but fail when server is offline.
Especially as if I turn "Only run when server is online" off it will happily run for infinity.

I totally get the not wanting it to clutter up the system though. Just note sure any suggestions to give there.
