### ISSUE TITLE
Reinsert the number of tasks on the dashboard page.

### ISSUE THREAD

**Issue by Shiru94** [gameserverapp/Platform#988]
First of all, I would like to say that I think the new display in the dashboard is a looks really good. 😊😁

But I would still be happy if the number of tasks created would show how many there are, or at least how many of them are active.
It was easier for me to see whether one of the tasks had been deactivated even though it shouldn't have been.

**Comment by mvaessen** [comment]
Thanks for reporting! I put back the numbers, while still trying to optimize for performance
